### ISSUE TITLE
set alpha of points

### ISSUE THREAD

**Issue by niallrobinson** [potree/potree#100]
Hi potree people - happy new year!! :tada: ,

I've been wondering if you can set/change the alpha of individual points in a cloud? Even just on/off would be nice. Any tips on where to go in the potree code to explore this if its not implamented? 

Thanks again

Niall

**Comment by m-schuetz** [comment]
Hello Niall!

Right now you can only set the opacity for the whole point cloud and if the opacity is smaller than 1, depth test will be disabled because it does not make much sense for unordered points. see https://github.com/potree/potree/blob/master/src/materials/PointCloudMaterial.js#L139

To set alpha/opacity of individual points, you'd have to add an additional geometry attribute in https://github.com/potree/potree/blob/master/src/loader/BinaryLoader.js#L86 and https://github.com/potree/potree/blob/master/src/loader/LasLazLoader.js#L186.
Then you'll have to pass the new attribute to the shader, see https://github.com/potree/potree/blob/master/src/materials/PointCloudMaterial.js#L114
and do something with it inside the shader https://github.com/potree/potree/blob/master/src/materials/PointCloudMaterial.js#L575

In any case, what would your use case for this feature be? Individual opacity raises some problems and it is usually necessary to order transparent primitives from back to front which can be very costly.
