### ISSUE TITLE
multiple views demo

### ISSUE THREAD

**Issue by yeyan00** [potree/potree#1014]
refer to three.js webgl_multiple_views

modify viewer.js
add the code at end in render() function
```

              {
                    // const viewport = [0, 0, width * this.overviewScale, height * this.overviewScale];
                    // default left corner
                    const width = this.scaleFactor * this.renderArea.clientWidth;
                    const height = this.scaleFactor * this.renderArea.clientHeight;
                    const viewport = [0, 0, width/4, height/4];
          
                    const camera = viewer.scene.getActiveCamera();

                   // test move camera position
                    camera.position.x += 100;
                    pRenderer.clearTargets();
                    pRenderer.render({ camera: camera, viewport: viewport });
                }
```

![image](https://user-images.githubusercontent.com/8616560/114538106-9045a980-9c85-11eb-8794-c35ea7ed66c6.png)

**Comment by arbertrary** [comment]
Hi, I found this issue after looking for a solution for a slightly different problem but that's not relevant here.

Do you maybe remember where exactly you added this code snippet in `viewer.js` because I can't seem to find a placement where it actually does anything.

By "at end in render() function" do you mean exactly after this line?

https://github.com/potree/potree/blob/develop/src/viewer/viewer.js#L2135

If you still have your code lying around I would love to see your entire changed version of the `render()` function.

**Comment by yeyan00** [comment]
> Hi, I found this issue after looking for a solution for a slightly different problem but that's not relevant here.
> 
> Do you maybe remember where exactly you added this code snippet in `viewer.js` because I can't seem to find a placement where it actually does anything.
> 
> By "at end in render() function" do you mean exactly after this line?
> 
> https://github.com/potree/potree/blob/develop/src/viewer/viewer.js#L2135
> 
> If you still have your code lying around I would love to see your entire changed version of the `render()` function.

yes！
i used version 1.7; the new version should be in this.renderDefault()
