### ISSUE TITLE
webgl issue: readpixels buffer not large enough for dimensions

### ISSUE THREAD

**Issue by webmandman** [potree/potree#1015]
Not sure why this is coming up now after having stable pointcloud views since september 2020. I use converter 2.0 and potree viewer 1.7.1. 

Issue 1: Height Measurement tool - I used to be able to click once to add a point, then a second click would add a second point giving me a measurement, but now the second click is not registered. I have to click and drag the first point to get a measurement. Its not how the tools worked just 2 months ago. and the code base hasn't been changed. I think the first click is actually doing two clicks and adds two points - that would explain why you immediately see "0.0ft" - so thats why I can drag the second point to my height and get a measurement. 

Plus, on initial load Chrome is throwing this caching error. and when I start using the tools it also throws the WebGL error. See image screenshot. 

Could it be possible that our automatic updates on Chrome browser has affected potree? 

Chrome version: Version 89.0.4389.128 (Official Build) (64-bit)
OS: windows 10 enterprise

I cant tie this to a Chrome update and a date. Not sure when Chrome was last updated, but I just noticed today that the potree measuring tools are not working as expected. 

![PotreeWebGL-readPixels-buffernotlargeenough](https://user-images.githubusercontent.com/991677/114643459-870b0b80-9c8a-11eb-90e5-74eb074e3975.PNG)

**Comment by midnight-dev** [comment]
See #991 particularly the comments from Nevernat. This has been a problem since Chrome 89 was released. It changed how events are bubbled/captured.

Haven't noticed the WebGL error, but it could be occurring just because the measurement tool can't get a proper fix on picks. Apply the relevant changes and see if everything works like it used to. Alternatively, Firefox or an older version of Chrome work fine.

**Comment by webmandman** [comment]
Thank you. That did it.

**Comment by midnight-dev** [comment]
Did it also take care of the WebGL error?

**Comment by webmandman** [comment]
Hello Ben,

WebGL errors did not show up anymore. I double checked right now too and
nada.

**Comment by webmandman** [comment]
But occasionally these caching errors do appear:
![image](https://user-images.githubusercontent.com/991677/114938007-6a3e1780-9df3-11eb-948c-6043b57ef614.png)

**Comment by midnight-dev** [comment]
Yeah, I'm not thrilled about those errors, but they _seem_ harmless enough to ignore, assuming your point clouds appear/behave as expected. Just to be clear, I'm not exactly sure how the voodoo magic works when fetching byte-level chunks from a monolithic binary file, but my working assumption is that Chrome (perhaps Firefox, too) is trying to cache partial ranges _or_ tripping over itself when looking for these pieces in its cache pool. 

I've been working almost exclusively with the older conversation format that yields **many** smaller but distinct files. It can be a pain to deal with the sheer amount of files, and the number of them seem to grow exponentially as the root bounding box volume increases. That said, the legacy format has the awesome benefit of being cache friendly, and it's very easy to spot a missing or possibly corrupt bounding box. If you see a request for r4444 and it returns an HTTP 404 code, then you just need to check if your upload missed that file. And if there is no r4444, then you have the enjoyable duty of re-running the conversation because something went wrong with indexing. Conversely, the monolithic file conversion leads to much faster & easier file management (including backups and sending deliverables), however, when you see errors like this that reference the large binary, it's hard to drill down to figure out if there's data corruption or a browser limitation or a network issue. Could even be the server discarding a request due to throttling. On the bright side, I've heard that the chromium dev community is working on better caching schemes for partial byte ranges, so this sort of problem will become easier to diagnose in the future. Hopefully.

Anyway, more information is needed. With tons of people watching this repo, surely someone reading this has extensive experience with the modern format. If anyone knows what's going on with the cache errors, some input would be welcomed here. Even if it's not a solution, sharing a small example cloud that reliably reproduces the error would greatly help bug hunting efforts.
