### ISSUE TITLE
Image 360 label

### ISSUE THREAD

**Issue by Matthieu-Fontaine** [potree/potree#1061]
Hello, I am currently working on the 360 images and I would like to place a label on the spheres. But I do not exactly or place the lines allowing this action. I'm sure under potree 1.8 thank you for your help. =)

**Comment by HeadLessHUN** [comment]
Hello I've done it for our use.  But i did so much more i cant just create a pull request from that.

But in short 

You could do that with Potree annotation. It will be drawn as 2d text. So the point cloud will not hide that.

I only created a Potree annotation on the constructor of the Images360 class.

And in the hoverhandler function i made it visible and set the title of the image.

```
//images360 class constructor
this.label=new Potree.Annotation({
			title: "",
			position:[0,0,0]
		});
		this.label.domElement.off("mouseenter");
		this.label.domElement.off("mouseleave");
		this.label.visible=false;
		this.labelVisible=false;


//end of hoverhandler (when there is a hovered element)
		if(this.labelVisible){
			this.label.visible=true;
			this.label.title=currentlyHovered.image360.originalName;
			this.label.position.set(currentlyHovered.position.x,currentlyHovered.position.y,currentlyHovered.position.z+this.meshSize*2);
		}
```

You will need some understanding of coding, because it has undefined variables (in 1.8) as ours is a heavily forked version.
![image](https://user-images.githubusercontent.com/10095691/128359436-61c0fb1e-d9dc-4310-a3c4-e3ae7c3bd019.png)

**Comment by MatthieuFont** [comment]
I'll try this, and it's true that potree is not accessible or at least not always intuitive the pleasures of the code :')

**Comment by Matthieu-Fontaine** [comment]
For the moment I have this error in loop I continue to try
Uncaught TypeError: Cannot set property 'visible' of undefined

**Comment by Matthieu-Fontaine** [comment]
I beautiful person i don't know how to explain but didn't work

**Comment by HeadLessHUN** [comment]
> I beautiful person i don't know how to explain but didn't work

I told you you will need some understanding of programming, because as i told you our version is heavily forked, you will need to define whats needed in the right context. But is suppose the label is not created in the constructor based on the error message...

because i think it is failing in this line.
```
handlehoover()
...
this.label.visible=true;

```

Did you placed the first part to the constructor of the images360 class?

**Comment by Matthieu-Fontaine** [comment]
So I place the first part of my code here:
![Capture](https://user-images.githubusercontent.com/73833231/128483546-70706665-c910-4d27-a5a7-78eb5f188726.PNG)
Then I written the necessary code in the loop at this time no error but nothing happens so make sure that it enters at the appropriate time in the loop allowing the display of the annotation and at this time appears the error
Uncaught TypeError: Cannot set property 'visible' of undefined


 Anyway I am a student looking to learn so thank you very much =)

**Comment by HeadLessHUN** [comment]
It is the constructor of a single Image360. 

scroll down and look for the Image(s)360 class.

And default it will not show anything you should enable this feature by default or set it from the gui by a button or something.

If you want te set it by default set the this.labelvisible to true in the constructor.

And you will need to hover over a sphere.

**Comment by MatthieuFont** [comment]
Now no more error but no annotation appears while the loop works, and the coordinates sound good (I display everything in the console)

**Comment by Matthieu-Fontaine** [comment]
Now no more error but no annotation appears while the loop works, and the coordinates sound good (I display everything in the console)
Ooh and I would like to know if we can see the other nearby sphere when we are in a 360 image?

**Comment by HeadLessHUN** [comment]
have you enabled by default the feature?

replace this in the constructor
this.labelVisible=false
to this
this.labelVisible=true

the second question it is possible but it is a little bit harder. And needs a different approach to unfocus and a different event for it to kick off. I used the movement if the user get away from the sphere then it will unfocus.

**Comment by Matthieu-Fontaine** [comment]
Yes everything was well activate but strangely it was not always stable so I opt for another method
->creates a box in the html:
    `<div id='labelsphere' onclick="document.getElementById('labelsphere').style.display = 'none'">labelsphere</div>`

-> and call this in mousemove:
if(currentlyHovered != undefined){															
				let label = document.getElementById('labelsphere');
				if(label != undefined){													
					label.style.top = (y) + "px";										
					label.style.left = (x) + "px";
					label.innerHTML = currentlyHovered.image360.filename;				
					label.style.display = "block";										
				}
			}else{																	
				let label = document.getElementById('labelsphere');						 
				label.style.display = "";										
			}

And everything works I'm not using your solution but thank you very much I will have understood new thing.

**Comment by HeadLessHUN** [comment]
Maybe this is better because it can be copied out. Where do you get the x,y position of the label? do you use a raycast? or just simply in one of the corner?

I would get the labelsphere div in the constructor and save it so you don't have to run "getelementbyid" on every single frame. It can cause some performance degradation if you calculate that 30-60 times in a second.

**Comment by Matthieu-Fontaine** [comment]
So for the moment the big part of the code is in the mousemove function that knows the location of the mouse in this way I lose after the performance test microsoft edge on average 5ms every 3 seconds for the moment I do not know or I could move it

**Comment by Matthieu-Fontaine** [comment]
Before on mousemove          ->let label = document.getElementById('labelsphere');
Now on  inputhandler constructor     ->this.label = document.getElementById('labelsphere');
