### ISSUE TITLE
Errors with compressed data: Corrupted Huffman code histogram

### ISSUE THREAD

**Issue by skinkie** [potree/potree#1125]
PotreeConverter development branch, which publishes a webpage with Potree 1.8.0. When creating a compressed file I by default end up with an error "Uncaught Corrupted Huffman code histogram". Sometimes the point cloud does not load at all, and requires a page refresh.

Uncaught Corrupted Huffman code histogram
readComplexHuffmanCode	@	DecoderWorker_brotli.js:584
readHuffmanCode	@	DecoderWorker_brotli.js:609
decodeHuffmanTreeGroup	@	DecoderWorker_brotli.js:975
readMetablockHuffmanCodesAndContextMaps	@	DecoderWorker_brotli.js:899
decompress	@	DecoderWorker_brotli.js:1025
decode	@	DecoderWorker_brotli.js:2046
onmessage	@	DecoderWorker_brotli.js:2128

**Comment by m-schuetz** [comment]
At least some of these errors are caused by inner nodes that have 0 points after all of them were promoted to the parent, but PotreeConverter did not set the point counter to 0. The viewer then tries to decode points that aren't there, throws an error, and stops processing the children that still have more points.

Error here: https://github.com/potree/PotreeConverter/blob/develop/Converter/include/sampler_poisson.h#L268-L275

Currently trying to add the inner node with 0 points case, and making sure nothing else breaks.

**Comment by m-schuetz** [comment]
So this is a two-parter, with fixes in viewer and converter. 

Viewer:
Some inner nodes actually have 0 points because all points got promoted to the parent, but the converter did not adjust the point count. The viewer therefore tried to decompress points that aren't there. However, these nodes can still be identified by having a byteSize of 0, which the viewer now uses to set the point count of the node to 0. Nodes with 0 points will no longer be decompressed.
* https://github.com/potree/potree/commit/33365e82a093768e9591939fe58a319dc9bf4ebe
* https://github.com/potree/potree/commit/10abf2135be1da9701e278c1b947dbfe00c9af53

Converter:
The corresponding fix in the converter makes sure that this doesn't happen to begin with, and that the affected nodes are correctly stored with a count of 0. I still have to test whether this causes issues in some other data sets, though.
* https://github.com/potree/PotreeConverter/commit/cd252b7f78ef2f9ee6b5f7f2ece29a046c21e6ec

Summary: Viewer identifies and corrects a mistake made by the converter (no reconversion needed). Converter stops making the mistake.
