### ISSUE TITLE
How to load PLY files?

### ISSUE THREAD

**Issue by kakai248** [potree/potree#147]
I have small ply files (around 37k points). But I can't find how to load them, there's no documentation about this. The examples don't show anything about it.

I found this http://potree.org/wp/ply-viewer/. And this is exactly what I want but with an updated version of potree (with the controls and distance measurement).

Can someone please guide me on how to load these files?

Thank you

**Comment by m-schuetz** [comment]
Ply loading has not made it into the three.js rewrite, yet.
I'll leave this open as a reminder to do that.

**Comment by martinheidegger** [comment]
As I understand, Potree only supports the _"potree format"_ for viewing pointclouds as it is optimized for the use with Potree.js and browser. [PotreeConverter](https://github.com/potree/PotreeConverter) should support the conversion of `.ply` files into the _potree format_. Please follow #108 for loading files without using the `PotreeConverter` directly.

_I am closing this issue since it is quite old and I am assuming that this comment explains everything. If it was premature, please reopen it!_
