### ISSUE TITLE
Unable to get property 'slice' of undefined or null reference

### ISSUE THREAD

**Issue by chuckyboy81070** [potree/potree#190]
I've noticed that some showcase examples do not load in IE 11.  The above error is visible in the console for the http://potree.org/demo/potree_1.3/showcase/tern_auscover_chowilla.html sample.

**Comment by m-schuetz** [comment]
As far as I know it's the las/laz demos that do not work in IE11. So all demos where you can choose "Appearance->Material->Intensity" won't work in IE.  
IE11 compatibility is mostly by accident and I do not actively target it unless it's trivial changes.
The reason is that it is [too far behind other browers, feature-wise,](http://kangax.github.io/compat-table/es6/) and probably won't see many updates now that the Edge browser is out. Edge, on the other hand, is not available for windows 7 so I can't target that browser either.

If you figure out how to fix this, I'd be happy to merge the changes.

**Comment by chuckyboy81070** [comment]
That was my fear....we've standardized on IE and will likely never waver from that.

Is it the las/laz format, or is it the Intensity?  If it were possible to display the Intensity otherwise, that would be great.

When I execute:

PotreeConverter.exe nm.las -o c:\potreeconverter\nm -p nm

Or 

PotreeConverter.exe nm.txt -f xyzi --intensity-range 255 -o c:\potreeconverter\nm -p nm

then I do not get an intensity option in Appearance->Materials.

**Comment by m-schuetz** [comment]
Does this work?

```
PotreeConverter.exe nm.txt -f xyzi -o c:\potreeconverter\nm -p nm --output-attributes INTENSITY
```

If it doesn't, try the same with a las or laz file as input next.

**Comment by m-schuetz** [comment]
> then I do not get an intensity option in Appearance->Materials

For most properties you'll have to use --output-format LAS (or LAZ).
This will store the whole octree in las/laz files.
The default output-format, BINARY, can support RGB, INTENSITY and CLASSIFICATION if you specify them with the --output-attributes parameter.

**Comment by chuckyboy81070** [comment]
yes!  The latter works great, even in IE.  Can more than one attribute be supplied as a parameter?

**Comment by m-schuetz** [comment]
Yes, you can specify all supported attributes in no particular order, e.g.
```
PotreeConverter.exe <input_file> -o <output_dir> -p <page_name> --output-attributes RGB INTENSITY CLASSIFICATION
```

**Comment by chuckyboy81070** [comment]
That's great.  Thanks so much for your help.
