### ISSUE TITLE
Point clouds doesn't render on mobile devices

### ISSUE THREAD

**Issue by psiekanski** [potree/potree#203]
On certain mobile devices, probably on all Windows Phone devices point clouds doesn't render. I tried to debug this issue via emulator in Visual Studio and it turns out that there is a security exception when Potree tries to create worker. Everything else renders juts fine. 
![wp_ss_20160112_0001](https://cloud.githubusercontent.com/assets/9296238/12264751/1a0cb2fc-b939-11e5-8f2d-11d3eb0d106e.jpg)

**Comment by m-schuetz** [comment]
Invisible / not rendered data sets seem to happen on some devices, network settings, etc. 
Unfortunately I can't realy trace these errors myself without the respective testing environments.
Could you tell me what kind of error message you're getting?
Or how emulating this in Visual Studio works?
If you're using IE / Edge, try Firefox or chrome instead. IE11 is no longer targeted as it is severely outdated.

I've recently had someone experiencing the same issue because of a proxy that blocked cross domain requests, even though they were explicitely allowed by the server hosting the point cloud data.

**Comment by psiekanski** [comment]
Error code is here:
Unhandled exception at line 5589, column 3 in http://potree.org/demo/potree_1.3/build/js/potree.js

0x800a139e - JavaScript runtime error: SecurityError

It occured in the line 5589 - var worker = new Worker(URL.createObjectURL(blob)); inside Potree.utils.createWorker function.

I test it on mobile IE because this is the only browser on Windows Phone that supports WebGL.

**Comment by m-schuetz** [comment]
There might be the option to load WebWorkers from a file instead of a string.
I've deliberately worked around this in the past by using strings instead, since accessing relative paths to source files inside other source files is a huge mess. 
I may give it a shot if time permits but IE11 support is very low priority unless trivial to do.

**Comment by m-schuetz** [comment]
Closing this here since support for IE11 has been dropped.
