### ISSUE TITLE
3d model position

### ISSUE THREAD

**Issue by dasha-5555-5** [potree/potree#217]
Hi! I need to display my 3d point cloud in right position, but I have as result bad orientation and model look as wrong inverted. Can anyone help me? Thanks.

**Comment by Totoico** [comment]
Hello, I encountered some issues as well. Any help would be appreciated. 

For instance, when exporting a Model from Blender to Potree PC (using potree converter), it seems that the pointcloud.position in Potree Viewer is not the same as the Local Space Position for the initial Point Cloud in Blender.

It is like Potree Converter is doing some translation & orientation stuff in order to always display in the Viewer the Point Cloud in the center of the Scene is it?

If I am right, is it possible to get the offset induced in the Viewer (in order to put back the PC in the Viewer at th same position and orientation it was in the Blender Scene)?

Thks,

**Comment by dasha-5555-5** [comment]
Hi, I am exporting my model from VisualSfm, not using Blender. I suspect that it may happens due to drone flight and flight direction..

**Comment by Totoico** [comment]
Hi, There is indeed an offset in potree, the pointcloud has a parent wich is an object 3D of three js with an offset which seems computed from the bounding box. 

On top of that, you must take care of the orientation. 

Potree has a flipYZ() function that may help you

**Comment by m-schuetz** [comment]
Hi. Yes, potree flips the y and z coordiantes by default and it also transforms the coordinate to the origin to preserve precision. Using flipYZ(), you can switch the Y and Z coordinates.
With viewer.toScene, you can transform coordinates from point cloud to scene coordiantes.
With viewer.toGeo you can transform from scene to point cloud coordinates.

If your point cloud is not in a map projected coordinate system but something like ECEF, then you'll get werd rotations because the data will be aligned to the center of the earth, rather then the X/Z bottom plane. The only way to fix this at the moment is to counteract this orientation yourself using three.js transformations or to convert your point cloud into a map projected coordinate system before conversion.

**Comment by dpieri** [comment]
I don't see `toScene()` or `toGeo()` anywhere in this repository. Could you point me to an example of how those methods would be implemented?

**Comment by Madg1c** [comment]
Not that I'd like to question the master on potree but thought it was viewer.toLocal for pointcloud to local conversion.
It's usage is already shown in previous post, but 
scenevar = viewer.toLocal(new THREE.Vector3 ( x , y , z )) ;

I can't get this to work properly though, when I run it through the debugger on the browser it works fine, but does nothing when put into the html script. 

		var coo = new THREE.Vector3(10, 10, 10)
		var invcoo = viewer.toLocal (coo)

In the case tested, both coo and invcoo are = (10,10,10). Can someone else check to see if they get the same? tested on Firefox and Safari.

**Comment by m-schuetz** [comment]
As an fyi, toGeo and toLocal will no longer be necessary in the next release and z will be the up coordinate.
This should make it easier to deal with georeferenced point clouds since you're using the same coordinate system that the point cloud uses. All point clouds still need to use the same map projection, though and the ECEF coordinate system will still pose the problem that point clouds will be tilted, rather than aligned with the ground.
