### ISSUE TITLE
Pointcloud doesn't handle occlusion with other scene objects, when Eye-Dome-Lighting Enabled

### ISSUE THREAD

**Issue by tldv** [potree/potree#231]
Hi, I have other three.js objects in the scene, but when I turn on Eye Dome Lighting of the pointcloud, the pointcloud becomes visible even when it should be occluded by the other scene objects. Which is weird because the pointcloud still handles self-occlusion properly. 

I guess potree isn't really expecting my use case of having other objects in the scene, but if you had any explanation or work around for this issue, it would be much appreciated.

Thanks in advance.

**Comment by m-schuetz** [comment]
Hi! The [EDL shader](https://github.com/potree/potree/blob/develop/src/materials/shaders/edl.fs) will need to write depth values using gl_FragDepth = exponentialDepth;
The issue here is that right now, only logarithmic and linear depths are readily available in the EDL shader. Logarithmic depth could probably be transformed to exp depth by [reversing this calculation here](https://github.com/potree/potree/blob/develop/src/materials/shaders/pointcloud.vs#L224). although it remains to be seen if this process causes precision errors. Alternatively, exp depth could be stored in the depth texture along with the log depth.

**Comment by m-schuetz** [comment]
Fixed in develop:

![image](https://cloud.githubusercontent.com/assets/6705073/22682655/2a35c9ba-ed14-11e6-87db-148ccce9d2d0.png)
