### ISSUE TITLE
Loading multiple scene in version 1.3

### ISSUE THREAD

**Issue by daviecahill** [potree/potree#235]
I can load multiple scenes in Version 1.4 which is great, but seems to crash quite frequently in Chrome and doesn't load in IE11.

Is there a way to load multiple scenes in version 1.3

This is how I am loading them in v1.4

viewer.addPointCloud("pointclouds/FPW-001/cloud.js", function(e){e.pointcloud.setName("FPW-001");});
viewer.addPointCloud("pointclouds/FPW-002/cloud.js", function(e){e.pointcloud.setName("FPW-002");});
viewer.addPointCloud("pointclouds/FPW-003/cloud.js", function(e){e.pointcloud.setName("FPW-003");});

**Comment by JWGmeligMeyling** [comment]
Yes, this is possible. You can add multiple pointclouds to the same reference frame in order for them to align properly and be visible next to each other. Because the datastructures of the two pointclouds are unaware of each others points and buckets, you're effectively loading twice as many points, causing your browser to crash faster than it usually would, due to Potree not cleaning up any fetched geometry and hitting the memory limit after a while (#222).

**Comment by martinheidegger** [comment]
It is possible right now _(there is [an example](http://potree.org/demo/potree_1.5/examples/gradient_colors.html) available)_. So I assume this might be an old issue and I hope its not an issue if I close this. Please reopen if that was premature.

**Comment by s80082350** [comment]
I am having troubles of add annotations and multiple scenes at potree, is that add when i type command at terminal ? (docker run -v $PWD/input:/Users/zixuanwang/Desktop/potree-converter-docker-master/input -v $PWD/output:/output potreeconverter PotreeConverter /Users/zixuanwang/Desktop/potree-converter-docker-master/input/car.las -p car -o /output/car -a RGB CLASSIFICATION)  is this a right place to add command for add scenes and annotations? and Also how does potree knows where to find different point clouds? (my version is 1.5RC)

**Comment by martinheidegger** [comment]
@s80082350 I answered in #428
