### ISSUE TITLE
exporting objects (measurements)

### ISSUE THREAD

**Issue by jubru** [potree/potree#247]
Hi Markus!

I have a prototype for exporting objects measurements into a GeoJSON or DXF file.
Would you like to integrate this code into potree?
![capture](https://cloud.githubusercontent.com/assets/12160142/18762541/74dc3a8e-8109-11e6-835a-de7e413220e6.PNG)

Best regards

Julien

**Comment by jubru** [comment]
http://p.sigeom.ch/fouille_CadSout/ 
[sidebar_HTML.txt](https://github.com/potree/potree/files/512969/sidebar_HTML.txt)

**Comment by m-schuetz** [comment]
Hi Julien,

I'm going to take a look at this now, thank you!

"EPSG:4326" has been hardcoded for the geojson exporter. 
Is the projection a requirement for geojson? 
I'm wondering because potree accepts projections in the proj4 format and not as an EPSG string.
Is it fine to export without projection information at all, or to export it with the proj4 string instead?

**Comment by m-schuetz** [comment]
And if I include your code, how exactly should I specify authorship?

**Comment by m-schuetz** [comment]
+What kind of viewer can you use to look at geojson files? I tried http://geojson.io but it seems like the crs specification has no effect and therefore doesn't display anything useful.

**Comment by monodo** [comment]
QGIS does the job perfectly. Here's the [x64 installer](http://qgis.org/downloads/QGIS-OSGeo4W-2.18.3-1-Setup-x86_64.exe)

**Comment by jubru** [comment]
Hi markus

The authorship are sigeom sa (www.sigeom.ch) and Ioda-Net Sàrl (https://www.ioda-net.ch/).

This code is experimental.

For the geojson, "EPSG:4326" is wrong, "EPSG:2056" is correct, sorry.
With QGIS, the Geojson import is correct. Labels are also exported.

For the moment, I do not think many people use the Geojson.
The DXF export is much used, especially by the architect.

**Comment by m-schuetz** [comment]
Thanks, qgis is working nicely

**Comment by m-schuetz** [comment]
I'll omit the crs information for now since there isn't an EPSG string associated with the point clouds.

> This code is experimental.

Cloud compare is able to read the DXF files and QGIS is able to read the geojson files. I'll consider this good enough, for now. I haven't touched any of these 2 formats before; if someone runs intro problems I'd be happy to accept fixes.

I've limited export to distance and area measurements for now since the exporters seem to be made specifically for these two?

Committed here: https://github.com/potree/potree/commit/7d5e9380db8f4a1badd4a9b2f0af0244cb0715e8

relevant files are:

* viewer/sidebar.js
* exporter/DXFExporter.js
* exporter/GeoJSONExporter.js

Thanks for the code!

![image](https://cloud.githubusercontent.com/assets/6705073/22788799/44c74b40-eee1-11e6-9ef9-e98b67414ede.png)

**Comment by jo-chemla** [comment]
Quick question: we can specify the projection in the PotreeConverter, which then stores it in the "projection" attribute of the clodu.js file. for example: 
`"projection": "+proj=utm +zone=35 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"`
This is a Proj4 string, not an EPSG, but I think you can reference it in the GeoJSON.

**Comment by jo-chemla** [comment]
In the Linked CRS, it seems that you can link files stored in relative or web location like this. This would mean you have to output a data.crs file along with the geojson file. I imagine you can store it as a named CRS, but I haven't seen an example of it yet.
```
"crs": {
    "type": "link",
    "properties": {
      "href": "data.crs",
      "type": "proj4"
      }
    } 
```
