### ISSUE TITLE
set orientation (heading)

### ISSUE THREAD

**Issue by giancan** [potree/potree#251]
Hi there, is there a way to set the direction of view with a parameter?
And also, is there a way to limit the view to a certain angle?
Say I have a wall facade and first I would like it to appear from the frontal view (not from back) and also I would like to avoid for someone to rotate the model and see it from behind.
Is there a way to make either of the two?
Thanks

**Comment by Madg1c** [comment]
look at viewer.camera, it behaves like a THREE.js camera, so there is alot of info on the web on it.

**Comment by giancan** [comment]
Thanks @Madg1c ,
I'm not an expert and I am trying to read the documentation.
If I may ask you some more help, should I modify the potree.js file or is it enough to something like
viewer.camera.lookAt(#,#,#);
after I load the cloud?
Thanks a lot

**Comment by dmercel** [comment]
The viewer.camera.lookAt command will not produce the effect I think you are looking for.  This is because it is executed at the wrong point in the render loop.  Instead you have to set the orientation of the camera by using **viewer.controls.target ()** method which uses the navigation controls to change the angle of view.  This is executed later on in the render loop so it actually updates properly.
That should give you what you need.

**Comment by m-schuetz** [comment]
In the next release, setting the view is done with

    // set camera position
    viewer.scene.view.position.set(x, y, z);

    // look at a specific position
    viewer.scene.view.lookAt(new THREE.Vector3(x, y, z));

    // set yaw rotation (left-right)
    viewer.scene.view.yaw = radians;

    // set pitch rotation (up-down)
    viewer.scene.view.pitch = radians;

**Comment by pomyslografia** [comment]
something like that?
viewer.scene.view.yaw = 10;
viewer.scene.view.pitch = 0;
viewer.scene.view.roll = -5;
