### ISSUE TITLE
testing potree-develop

### ISSUE THREAD

**Issue by jubru** [potree/potree#264]
Hi Markus,

I try to test the develop branch (28.12.2016) for my curiosity. The annotations.html and viewer.html files don't work on my server.

The web console gives the following error:

Uncaught TypeError: viewer.setScene is not a function
     At annotations.html: 78

or:

Uncaught TypeError: viewer.setScene is not a function
     At viewer.html: 80

Should something be corrected to use the develop branch?

Best regards
Julien

**Comment by m-schuetz** [comment]
Hi Julien,

It's mostly because I haven't updated the builds with every commit. Also because there are some lines that don't work with the latest commit, yet, but mostly because I didn't do new builds.

Take a look at https://github.com/potree/potree/blob/develop/docs/build.md to see how to build potree. 
Even so, you may have to wait a bit until develop is ready for a new build. Will let you know.

**Comment by m-schuetz** [comment]
This commit to develop now contains a new build and a working demo in examples/viewer.html:
https://github.com/potree/potree/tree/0e1780ffcdf30e275ed26ed3f2c26ca32c4a6e0d
