### ISSUE TITLE
combine with three.js?

### ISSUE THREAD

**Issue by foobarbecue** [potree/potree#28]
Would it be possible to turn potree into a loader for three.js?

**Comment by Polak74** [comment]
Hi @m-schuetz
I read posts before, I understand Potree and three is merge. 
We try to move some elements/pointscloud/obj by drag like this page https://threejs.org/examples/?q=Inter#webgl_interactive_draggablecubes
But we don't find solution, some conflicts I think. 
Do you have some idea?
Thanks in advance.

**Comment by pushpaklive** [comment]
Hi @m-schuetz 

I am referring this link --> **http://potree.org/demo/potree_rewrite/** to render a pointcloud and threejs mesh under a single scene. But, I am unable to render the point cloud since the server is unable to load the octree directory 'data' and am getting below error:

**Failed to load file! HTTP status: 404, file: resources/pointclouds/lion_takanawa/cloud.js/../data**

Could you please tell where to host the 'data'(OctreeDir) directory. Currently I have kept the 'data' directory and cloud.js under same folder but unable to load the point cloud.

Thanks  :)
