### ISSUE TITLE
Pick problem

### ISSUE THREAD

**Issue by ShY81** [potree/potree#295]
Point Picking is not working properly since 1.5 (only some points are OK)
![2017-02-18](https://cloud.githubusercontent.com/assets/25864027/23093283/fe821ac4-f5f3-11e6-981c-c4ea96f07c68.jpg)
- This functionality had no problems on 1.4

**Comment by m-schuetz** [comment]
Right, seems like picking doesn't work for the highest detail nodes.

**Comment by ShY81** [comment]
@m-schuetz nodesOnRay seems to do fine, any idea?

**Comment by BenjaminLoesch** [comment]
same problem here... are there any ideas or workarounds?

**Comment by m-schuetz** [comment]
Some insight on this one: 

After the update to the new three.js, picking works by finding which octree nodes are relevant for picking and then fetching the necessary webgl buffer IDs from threejs, like this:

    let positionBuffer = renderer.properties.get(geometry.attributes.position).__webglBuffer; 

This only works if three.js has previously loaded the buffers to the GPU, i.e. if threejs already rendered that node at least once. The assumption is that this should have been the case since we're only picking points that can be seen on the screen. In some cases, renderer.properties.get(geometry.attributes.position) does not find any previously loaded buffer so we'll have to figure out why. 

Some relevant lines of code in WebGLRenderer that could be related to this bug:

```function projectObject( object, camera ) {```

```if ( object.frustumCulled === false || isObjectViewable( object ) === true ) {```

```
// the nodes we're trying to pick are missing in renderList / opaqueObjects
pushRenderItem( object, geometry, material, _vector3.z, null );
		function renderObjects( renderList, scene, camera, overrideMaterial ) {
			for ( var i = 0, l = renderList.length; i < l; i ++ ) {
```

**Comment by davijo** [comment]
It seems to have changed quite a lot in the dev branch of THREE.js, maybe updating could be a solution: https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L1303

I'm currently trying to get that to work. Some necessary changes noticed so far in the pick function:
`renderer.state.setDepthTest(pickMaterial.depthTest);`
->
`renderer.state.buffers.depth.setTest(pickMaterial.depthTest);`

Though, now I am experiencing INVALID_OPERATION error:
![image](https://cloud.githubusercontent.com/assets/8625487/24541225/3d96c072-15ff-11e7-8eb8-09fa3df7d8de.png)

I'll see if I can come up with anything.

**Comment by m-schuetz** [comment]
Thanks for the hints about the newest threejs. Will have to update soon.

As for the picking, the problem was something very different. Currently, the hrc hierarchy files contain the hierarchy and the number of points in a node. Unfortuantely, these numbers are wrong. Rendering used correct number of points as calculated by the size of a node divided by the byte size of a point. Picking, on the other hand, used the wrong number of points from the hierarchy files.

Picking now uses the same value as rendering. The number of points in the hiearchy will have to be fixed.

**Comment by davijo** [comment]
Excellent @m-schuetz , thanks for figuring out what the problem was!

On a side note:
I noticed something in the commit that probably shouldn't be there:
https://github.com/potree/potree/blob/develop/src/Potree.js#L382
`let allowedNodes = ["r", "r4", "r40", "r402", "r4020", "r40206"];`

**Comment by m-schuetz** [comment]
You're right, that should not have been committed. Fixed it. :)

**Comment by adnan-wahab** [comment]
i'm getting this problem on the latest develop

rollbar.min.js:2 TypeError: renderer.state.setDepthTest is not a function
    at Potree.PointCloudOctree.pick (vendor-039c4c8….js:125260)
    at Function.getMousePointCloudIntersection (vendor-039c4c8….js:126278)
    at OrbitControls.zoomToLocation (vendor-039c4c8….js:123277)
    at OrbitControls.dblclick (vendor-039c4c8….js:123221)
    at OrbitControls.dispatchEvent (vendor-039c4c8….js:74014)
    at InputHandler.onDoubleClick (vendor-039c4c8….js:121939)
    at HTMLCanvasElement.t._rollbar_wrapped.t._rollbar_wrapped (rollbar.min.js:1)
    at ZoneDelegate.345.ZoneDelegate.invokeTask (zone.js:425)
    at Object.onInvokeTask (core.es5.js:3881)
    at ZoneDelegate.345.ZoneDelegate.invokeTask (zone.js:424)

**Comment by adnan-wahab** [comment]
i tried using a couple different versions of 3js 85-88 to no avail
