### ISSUE TITLE
Custom Vertex Shader seems to have wrong Normals

### ISSUE THREAD

**Issue by jo-chemla** [potree/potree#337]
Hi all, 
I set up the dev environment and modify the pointcloud vertex shader - I'd like to set up a matcap material for the point cloud. To do so, I need the normal coordinates, and it seems they are not correctly set when I need them. 
I exported a potree with the converter using the tag `-a NORMAL` and `-a RGB NORMAL` and got two potree dataset to test on from the lion las example - I also used CloudCompare to convert normals computed to HSV and have that color version of the normals if needed. Then, I modify the lines following `#elif defined color_type_intensity`, and I can see my modifications work correctly with different parameters. However, when I use the normal, unexpected behaviors happen, and to troubleshoot, when I set `vColor = (modelMatrix * vec4(normal, 0.0)).xyz;` I get a black point cloud - same if I use `vNormal`. 
Do you know if the normal is set at that time oin the shader? Thanks in advance, Jonathan

**Comment by jo-chemla** [comment]
Ok might have found it: In 
 - `Potree.PointCloudArena4DGeometryNode.prototype.load` and 
 - `Potree.LasLazBatcher` functions,   

You set the `positions`, ... Float32Array arrays, either from data or from array, and then call `geometry.addAttribute('position', new THREE.BufferAttribute(new Float32Array(positions), 3));`. 

However, for normals, in both cases you set `geometry.addAttribute("normal", new THREE.BufferAttribute(new Float32Array(numPoints*3), 3));`, which are thus never set from data. It is therefore null vector for each point of the cloud. Can you point me in the right direction to update it ? 
Again thanks for your time.

**Comment by jo-chemla** [comment]
For reference, found the relation between cloudcompare generated HSV normals and real world normals : 
```n = normalize( normalMatrix * (vCol * 2. - vec3(1.,1.,1.)) )```
Simple inversion of formula ccNormalVectors.cpp / ccColor::Rgb ccNormalVectors::ConvertNormalToRGB(const CCVector3& N)

**Comment by martinheidegger** [comment]
Depending on the output format of the PotreeConverter, the logic to load is different. Did you generate `las` files? 

Binary files use normals data here: [`BinaryDecoderWorker.js#L187`](https://github.com/potree/potree/blob/58c289c707406224544fd216d1777b671250c9b9/src/workers/BinaryDecoderWorker.js#L187) but it the LAS format _(and laz by relation)_ do not have normals support in potree [`LASDecoderWorker.js`](https://github.com/potree/potree/blob/58c289c707406224544fd216d1777b671250c9b9/src/workers/LASDecoderWorker.js) because [the las file format](https://www.loc.gov/preservation/digital/formats/fdd/fdd000418.shtml) does not support normals as far as I can tell.

**Comment by jo-chemla** [comment]
You are right, I am using las files. Will try with a binary file as soon as I can, thanks for pointing this out!
