### ISSUE TITLE
Annotations Potree 1.4

### ISSUE THREAD

**Issue by jorge-17** [potree/potree#361]
Hi everyone.

i'm wonder if i can add some annotations over the point cloud and how?
i'm using potree v1.4

**Comment by ceciliaconsta3** [comment]
Hi @jorge-17, the simplest way to add an annotation would be to reference the <code>annotations.html</code> file and update the code there.

I'm not sure how much of potree you've seen so far but here's some steps to get you started:

1.  Open the<code>annotations.html</code>inside your browser - it's in the examples folder on root
2. Zoom/pan, whatever you need to do to modify the camera so that it displays the spot you would like your annotation to show
3. Toggle the left menu and select "Scene"  - displays the Camera Position and Target coordinates
4. Open the <code>annotations.html</code> file in a code editor or IDE
5. Place your custom Camera Position and Target coordinates in one of the annotations like so:
 <code>.addAnnotation</code> = Camera Position
 <code>"cameraPosition"</code> = Camera Position
 <code>"cameraTarget"</code> = Camera Target
6. Go back to your browser and check the position and behavior of that annotation - make tweaks as needed

Use these steps to add additional annotations to other pointclouds.

**Comment by jorge-17** [comment]
Thanks for the answer @ceciliaconsta3, I could add the annotations as you explained.
![capturaannotation](https://user-images.githubusercontent.com/16123655/31288883-6206aacc-aa8c-11e7-84b2-57d1cd971096.PNG)
