### ISSUE TITLE
Potree renders a line

### ISSUE THREAD

**Issue by joakimfj** [potree/potree#383]
All models me and three other people have converterted end up like this.
The points in the pointcloud are aligned along one axis only.

![screen](https://user-images.githubusercontent.com/31102530/29415618-e57d784a-8363-11e7-8005-8d9a2e0ad0b9.png)

Anyone on why?

Example is viewable here: http://potree.dronegruppen.no/E134/E134.html

**Comment by potree** [comment]
As mentioned on twitter, it's likely that your input point cloud is stored with lat/long/height coordiantes. Lat/lon are very small values compared to height, which is why you get a single vertical line. You'll have to reproject your point cloud to an euclidean coordinate system before converting with the PotreeConverter.

**Comment by martinheidegger** [comment]
@potree would it be possible/reasonable to add a flag to the PotreeConverter that adds that processing step?

**Comment by joakimfj** [comment]
Thanks for the reply. Any tips as to how you go about doing that?

**Comment by martinheidegger** [comment]
@joakimfj did you find a solution?

**Comment by joakimfj** [comment]
Yes, it seems that by not assigning any coordinates to it works. I use RealityCapture. But now I cant even run the converter at all.
