### ISSUE TITLE
Custom pointcloud shader

### ISSUE THREAD

**Issue by m-schuetz** [potree/potree#42]
At the moment, I've made a change to the three.js version that comes with potree, to make the minimum size of points 2pixels. So, if you use the official three.js version, you'll end up with a different point size.
- Make a custom shader so everyone can use the official three.js build and get the same results
- Might be a good time to think about normals and lighting.
- Maybe change the point size scale? As of now, 0.01 is a good choice. Seems odd but there could be a meaning to it. ( like pointSize = diameter in euclidean space? That could be pretty useful, actually. )

**Comment by jo-chemla** [comment]
Hi Markus, 
I would like to set a custom shader material for the point cloud, but when doing so, I get a `ThreeJS ShaderMaterial` instead of a `Potree PointCloudMaterial`, so I get the following error
```
potree.js:12437 Uncaught TypeError: scope.pointclouds[i].material.setClipBoxes is not a function
    at Potree.Viewer.update (potree.js:12437)
    at loop (potree.js:12943)
```
What I've done is either 
 - define a `shaderMaterial `from scratch and set vertex and fragment shaders - a bit modified from the current shaders of the point cloud
 - clone the `pointcloud.material` using the threejs function, set its `VertexShader` and `FragmentShader` to what I want, but again same result
 - update the shaders of the material of the point cloud directly, but the changes are not applied. 

Can you tell me how I can achieve this feature of modifying portions (x, y, z, vcolor) of the shaders ? 
Thanks a lot for your help again, 
Jonathan

**Comment by Zvyozdo4ka** [comment]
@jo-chemla Hi, Jonathan! I guess you have achieved yourself results. Could you share you experience? 

Could you explain how does the shaders work? In what language have they been realized? Do you have any documentation regarding shaders?

**Comment by 2chen** [comment]
@Zvyozdo4ka a few years late to the party, but this might be useful for someone: I was able to set a custom shader by extending the PointCloudMaterial class and overriding the `updateShaderSource` function (which resets the shaders to defaults) to load custom shaders instead.
