### ISSUE TITLE
Pointclouds into separate drive

### ISSUE THREAD

**Issue by Raquel0** [potree/potree#586]
Hello!
Thanks in advance for your time and effort.
My case is what follows:
I built potree into my SSD drive (C:) but y want to keep the pintclouds into my HDD (E:). When i specify an absolute path to the pointcloud
	`Potree.loadPointCloud('E:/Pointcloud/mypointcloudfolder/cloud.js', "PC", e => {`

no pointcloud is loaded and the only thing y find in the console as error is:

> SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data[Saber más] POCLoader.js:22:16
load/xhr.onreadystatechange
POCLoader.js:22:16

Sorry if this a silly question but i'm coming crazy to find a solution.
Thank you very much! :)

**Comment by potree** [comment]
You can't load point clouds directly from disk inside a web browser due to browser security policies. 
You can, however, try [PotreeDesktop](https://github.com/potree/potreedesktop) which is potree but running as a native App via Electron. 
Alternatively, you can set up a local web server, store your point clouds in the web server htdocs directory, and then load them from there via some http://localhost url.
