### ISSUE TITLE
too more data  freeze

### ISSUE THREAD

**Issue by a599219798** [potree/potree#750]
Hello, I now use Potree to load the data of a street in a 3D point cloud. The numbers on the street and buildings are all independent data files. But now more than 70 data will get Freeze when loading. Is this normal? Is there a setting similar to OSG for the near and far clipping planes?

**Comment by m-schuetz** [comment]
Hi. Potree is mainly targeted at few large point clouds so you'll run into issues if you've got a whole lot of separate data sets. It's not surprising that 70 data sets will freeze it. You may have to merge your individual point clouds in fewer larger ones, or make sure that only a couple of them are displayed at a time. Right now there also isn't the option to control the clipping plane yourself, since it automatically adjusts to the extent of the point clouds.

Both are good points, though, and I will keep them in mind for a future rewrite in WebGPU. Unfortunately it likely won't happen with the WebGL version of Potree anymore.
