### ISSUE TITLE
Query scene via arbitrary ray (not screen point)

### ISSUE THREAD

**Issue by rfrenz-avio** [potree/potree#758]
Hi, I have a need to query the Potree scene to find its intersection with an arbitrary ray.  This is sImilar to point picking , but I'm computing the source and direction of the ray from other user input.  Further, the Potree div element may not be onscreen at the time I need to query it.

Reading the code, it seems pointcloud.pick has an implicit requirement that the params argument contains viewport coordinates x, y

[https://github.com/potree/potree/blob/72748db38fd46a98c4d0800a70b1fe2570365152/src/PointCloudOctree.js#L818]

Any idea how I could implement this?  Is there something similar to pointcloud.pick(ray)?

Thanks
-Ryan

**Comment by JulianRuiseco** [comment]
Hey. 

Potree will only load a subset of the total cloud into the client. The reason that they raycast requires a viewport position is because it is going to try to find the point based on the pixel projection of the points onto the canvas. Which is incredibly fast, and uses the gpu side trimming. 

If all you want is to find an intersection of something you know to be on the loaded point cloud. You should make an octree of the points in the scene. Which you can do by crawling the points that have been loaded onto the view object (window.viewer.scene.pointcloud[x].children). Note that if the children that are loaded change, the tree will no longer be valid. Making a tree is not a real time endeavor either.

If you are hoping to shoot a ray at all the points. You either have to stream every point from the server into your octree (very very bad). Or you can do it server side with pdal or an equivalent.

In either case, shooting a ray at the entire cloud is not a trivial addition

**Comment by jo-chemla** [comment]
This works for me, if points were already loaded - so the scene is not empy, might be good to set view position and lookat first, and then do the raycasting. 

```JS
var raycaster = new THREE.Raycaster(origin, direction),
    intersects = raycaster.intersectObjects(scene.pointclouds, true),
    closest = intersects.reduce(function(p, c) { return (p.distance < c.distance) ? p : c}, false);
if (intersects.length > 0) {
    center = closest.point;
}
```

**Comment by rfrenz-avio** [comment]
Thank you very much @jo-chemla, this works quite well.  For some reason I assumed that the points were not intersect-able like normal 3JS objects :)

-Ryan

**Comment by m-schuetz** [comment]
Thanks, @jo-chemla !
