### ISSUE TITLE
3D transformations of the whole viewer

### ISSUE THREAD

**Issue by VioletteA** [potree/potree#767]
Hello,

I'm currently working on a project that requires displaying a large number of very different resources in the same viewer. Instead of using a single instance of Potree.Viewer, I plan to load several: one for each family of resources to display. In order to allow their registration, I would need to be able to manipulate each of these "viewers" as if they were 3D objects. But currently, they inherit from the EventDispatcher class and do not support 3D manipulations.

`class Viewer extends EventDispatcher { }`

Would it be possible to modify this class to inherit instead from the THREE.Scene or THREE.Object3D class? 

`class Viewer extends THREE.Scene { }`

Or, if not possible, to add a method to allow the application of a 3D transformation matrix so we can do as follows ?

`Viewer.applyMatrix ( new THREE.Matrix4(……) )`

Thanks

**Comment by m-schuetz** [comment]
Hi, did you manage to create multiple viewers? I'd guess that this isn't possible or won't work as expected since the viewer is meant to encompass the data and behaviour of the whole application.

The current architecture of Potree may not allow you to easily group different family of resources directly, and have a applyMatrix function. The problem is that many functions and tools depend on the current behaviour where the point cloud matrices aren't modified. Instead, I'd suggest to write your own javascript module that keeps track of resources/family of resources with the desired behaviour, then call Potree related functionality as needed, something like:

```

class Aioli{

	constructor(potreeViewer){
		this.potreeViewer = potreeViewer;
		this.resources = [];
	}
	
	loadResource(resource){
	
		let {resources, potreeViewer} = this;

	
		resources.add(resource);

		if(resource.type === "pointcloud"){
			
			Potree.loadPointCloud(resource.url, resource.name, e => {
				let pointcloud = e.pointcloud;
				
				potreeViewer.scene.addPointCloud(pointcloud);
				
				resource.sceneNode = pointcloud;
			});
			
		}
		
		...
	}
	
	applyMatrix(matrix){
	
		// might be necessary to disable matrixAutoUpdate for threejs nodes,
		// otherwise three.js would recompute the matrix from position, rotation and scale in each frame
		// sceneNode. matrixAutoUpdate 
	
		for(let resource of resources){
			
			if(resource.sceneNode){
				resource.sceneNode.applyMatrix(matrix);
				
				// or maybe one of those may be the correct ones to set a new matrix instead of applying it in addition to the current one.
				// or sceneNode.matrix.copy(matrix);
				// or sceneNode.matrixWorld.copy(matrix);
			}
			
		}
		
	}

}
```

If you have resources other than point clouds, you can also put them in one single THREE.Object3D ( or a single Object3D per resource family) and add that to viewer.scene.scene.

If your goal is to have different matrices for different resource families, I'd definitely go for creating an Object3D per resource family. If different matrices imply different geographic projections, things might get a little tricky. Potree doesn't really do proper handling of different projections, it just takes the one of the point cloud and goes with it. If another model has another projection, you might have to reproject all of them into the same coordinate system of the point cloud. If you have different point clouds with different projections, then things will get really tough and I have no good solution for that.

**Comment by VioletteA** [comment]
Hi,
following your answer we changed our strategy, by managing the registration upstream in our pipeline in order to avoid as much as possible the transformations in the viewer.  It was a bit tricky but it eventually works.
To manage independently the behavior of the different projects in the viewer we also had to create a new object class "aioliProject" which contains both point clouds, oriented images and annotations. Thanks again for your help, now I can close this issue.
