### ISSUE TITLE
PotreeConverter.exe options for best results and maximum resolution

### ISSUE THREAD

**Issue by BobJones2050** [potree/potree#771]
Hello, I am using the latest version of PotreeConverter.exe.  I've had little time to work with it and I apologize for a very simple question. But, could someone just give me a command line (and options of course) that will generate the best results and maximum resolution on the final webpage?

I've run it like this (on Windows): PotreeConverter.exe .\points.las --generate-page points

points.las is just over 3 GB in size.  PotreeConverter.exe creates a pointcloud directory that contains about 14K files with a total size of 1.75 GB.  I'm assuming it is breaking that 3 GB file up into smaller pieces so they can be fed to the web browser as/when needed.  The website displays the results fairly well but not as good as it could.  Do I just need some different options?  I've tried the --spacing option some but little else.

Also, do I need to put the original points.las file on the website itself?  I would assume not but I could also see where it might pull parts of the data from it "at runtime".

Anyway, I apologize again for the simplicity of this question and the fact that I haven't been able to just try some simple things (such as transferring points.las up to the web site (although not that easy actually!)).

Thank you.

**Comment by HeadLessHUN** [comment]
Hi there!

With the default settings the converter converts all of the points. so it should be the same as your input.

Maybe you should just set the point budget higher? And tweek the settings, like point render type, point size, change t high quality render method (needs better gpu).

i usually use this config...

these are the viewer configurations
```
		viewer.setFOV(60);
		viewer.setPointBudget(10*1000*1000);

		//hqRenderer
		viewer.useHQ = true

		//navigation Cube toggle
		viewer.toggleNavigationCube();

		//Navigation mode: fly
		viewer.setNavigationMode(Potree.FirstPersonControls);
		viewer.setMoveSpeed(20);
```

and these are the pointcloud material settings, i usually use...
```
material.pointColorType = Potree.PointColorType.RGB; // any Potree.PointColorType.XXXX 
material.size = 1;
material.pointSizeType = Potree.PointSizeType.FIXED;
material.shape = Potree.PointShape.CIRCLE;
```

these should be set in the generated html file...

But of course i'm too excited, how to determine which is the best way to convert our clouds... which is the best file size for the html wokrload... because we can tweek them by number of levels, and the point count in the first level...

**Comment by BobJones2050** [comment]
Thank you for your response. I will definitely try those settings out. I just haven't been able to spend very much time on it. Was looking for a quick win!

If anyone has any further ideas or comments, please let us all know. Thanks!
