### ISSUE TITLE
Potree Javascript API Documentation

### ISSUE THREAD

**Issue by jmdollosa** [potree/potree#787]
Hi everyone, 
I've been working with Potree for my project and would like to ask if there is a Wiki or an online documentation that explains in details how Potree library work? 

If someone could provide me some resources I might consider to volunteer creating API Documentation for it.

Example:
I would like to know what does the method `setEDLEnabled` do.

`
window.viewer = new Potree.Viewer( document.getElementById("potree_render_area") );
viewer.setEDLEnabled( true );
`

Thank you!

**Comment by midnight-dev** [comment]
Sorry about the late response. I meant to answer this a couple weeks ago.

There's not much in the way of API documentation that I know of, but there are a few markdown documents in Potree's `docs` directory. The most helpful and relevant ones are `scripting.md` and `potree-file-format.md`. These can be easily rendered (previewed) in the current version of VS Code by right clicking the file and selecting "Open Preview" like so:

![image](https://user-images.githubusercontent.com/47105073/79960318-e0ab7200-844a-11ea-9842-4a583e0f67f2.png)
 
I'd like to start putting doc blocks in some key areas so we can get more use out of IntelliSense and doc generators. But there's no way that's going to happen overnight. Potree is already pretty big, so more than likely it's going to be a community effort.

Right, so, `viewer.setEDLEnabled( true );` enables EDL, but it's not immediately obvious what that stands for. **EDL is Eye Dome Lighting.** Enabling it costs a little more resources and can make things look more realistic / less static. Although this isn't noted anywhere (not that I could find anyway), EDL may interfere with some features. For instance, using Eye Dome Lighting with standard splat quality will make the Navigation Cube disappear, but it works as expected with high quality splats. It's a glitch - not the intended behavior. Hopefully it will be fixed in the near future, but it's worth a mention that you should test your new code & graphical elements with and without EDL enabled so your feature doesn't disappear from the render area when someone toggles the option.

Speaking of which, this is the relevant option in the UI under "Appearance":

![image](https://user-images.githubusercontent.com/47105073/79959722-11d77280-844a-11ea-885f-c133ca35711b.png)

Hope that helps.

**Comment by jmdollosa** [comment]
Thanks for pointing this out @midnight-dev. 
Will just check the docs from there.

**Comment by AntoninGuilloux** [comment]
Hi,
I am new to potree, and would like to learn more about its functionnality... but as of today the docs/ directory only contains images. Is there a way to find the documentation.
Thank you!

**Comment by midnight-dev** [comment]
@AntoninGuilloux Check the master branch. It's a couple months old, so it's docs didn't get deleted yet. I'm not clear on why all of the markdown docs were removed, but it's not the first time that it's happened. 

Double check the code
