### ISSUE TITLE
 It is possible to upload a classification to a model unclassified in potree?

### ISSUE THREAD

**Issue by rjose97** [potree/potree#799]
First of all thank you for this wonderful project. Which facilitates programmers and brings 3d modeling closer to users

I am trying to add from javascript a classification to the 3d model that we are visualizing. This model has no classification. When generated with PotreeConverter the classification was not taken into account.

The classification is saved in "`viewer.scene.pointclouds [0] .pcoGeometry.root.geometry.attributes.classification`" on the different nodes. But I am not able to generate its structure.

I attach an image with classification (that I am able to work with) and another one without classification and I am not able to generate the structure.

Thanks in advance, regards
![modelwithClass](https://user-images.githubusercontent.com/54666078/80462973-cafce780-8937-11ea-8734-cd428db53f7e.PNG)
![modelwithoutClass](https://user-images.githubusercontent.com/54666078/80462976-cb957e00-8937-11ea-9371-45f6350cbd19.PNG)

**Comment by smcavoy12** [comment]
Hi rjose97,

If I'm understandning correctly, I think classifications aren't supported in the standard converter format, only as .laz.  I can see from your screenshot it's .bin instead of .laz. So your potreeconverter line should be:

`PotreeConverter.exe "C:\yourfile" -o Z:/ --generate-page PageName  **--output-format LAZ**  ` 

adding that output format bit at the end should make all the difference.

**Comment by rjose97** [comment]
@smcavoy12 Not exactly. I want to do it only on the pootree runtime structure. That is in javascript / webGL.

@m-schuetz Would it be possible to realize it? Would it be a future functionality? Thank you in advance

**Comment by m-schuetz** [comment]
Unfortunately I don't have to resources to work on something like this at the moment. It could be a consideration for the WebGPU rewrite, but there are several issues that may not have good solutions. Mainly, Potree only works on a subset of the full data so any classifications you generate at runtime may be missing higher levels of detail that were not loaded.

Closing this here, since it's not something that will be worked on atm.
