### ISSUE TITLE
relicensing potree

### ISSUE THREAD

**Issue by josch** [potree/potree#810]
Hi,

I noticed via [twitter](https://twitter.com/m_schuetz/status/1220819159711436800) that you are pondering to change the potree license. As a Debian Developer I wanted to ask you to please consider choosing a license that complies with [Debian's free software guidelines (DFSG)](https://wiki.debian.org/DFSGLicenses).

If I understood you correctly, then your problem is missing attribution from companies using potree. The current license enforces companies to mention "http://potree.org" and "Markus Schütz" if they make potree available to their users in source or binary form. If any company is doing that without mentioning "http://potree.org" and "Markus Schütz" then they are in violation of the license. So what I guess companies are doing instead is to make the web interface available to their users but not the software used to create it. In that case, the current license indeed does not require them to give any mention to the original copyright holder or the license.

A license that might do what you want is the AGPL. It was specifically created for code providing web services and forces the provider of the web service to also attribute the original copyright holder and deliver the source code behind it to their users.

This report is not meant to be advertisement for the AGPL (many find it way too restrictive) but it's the only license I know which explicitly covers the use case of software that creates content delivered over a network where the user never receives the actual source code itself. All other common licenses (GPL, BSD, MIT...) only require attribution if the code itself is distributed which is not the case for web applications. I personally am not in favour of the AGPL (it is probably the most restrictive free license) but I wanted to suggest it to you before you end up choosing a license that is not DFSG-free.

Thanks!

cheers, josch

**Comment by m-schuetz** [comment]
Thanks for the suggestions. I was actually thinking about dual licensing where the default would be GPL, and companies who're not comfortable with that have the option to purchase a proprietary license.

**Comment by josch** [comment]
I am not a lawyer, but the GPL also only requires attribution if your code itself is distributed to a third party. The current license also requires attribution in those cases. So if somebody distributes your code (in compiled for or as source code) without attribution today, then they are already in violation of the current license. In terms of distributing the *output* of the code (the website) to third parties, the GPL does not add any additional protections over the current license.

**Comment by m-schuetz** [comment]
As far as I understand, GPL or AGPL doesn't stop anyone from simply using PotreeConverter as a software-as-a-service application. Companies could still charge users for using Potree, without having to contribute anything back.

**Comment by pierotofy** [comment]
You are correct. A company can take Potree as-is and monetize it without contributing anything back.

What GPL (and AGPL to a greater extent) can enforce, is that customizations and patches to Potree have to be contributed back. Currently companies can customize Potree, but don't have an obligation to share their modifications. AGPL enforces that. GPL is less restrictive, but since the codebase is mostly Javascript it would work well too.

An interesting read: https://drewdevault.com/2020/07/27/Anti-AGPL-propaganda.html

**Comment by m-schuetz** [comment]
My beef is mostly with SAAS type monetization of Potree by companies that don't fund Potree in return. They don't need to change the converter source so AGPL doesn't do much, and since the monetization comes from the hosting service, making them release their customized version of Potree doesn't help fund future development of Potree. So I'm afraid AGPL won't really convince SAAS services to fund Potree. 

Since there is uncertainty regarding my future employment at the university and therefore the future funding of Potree, I'll now have to find a way to convince companies to fund the ongoing development of Potree. And currently I'm leaning towards something like this:

* Starting from version 2.0, Potree will be free for non-commercial and non-government use.
* Government agencies and organizations that include Potree in a commercial product or service will need to acquirce a paid license.

That's what I'm leaning to right now. However, if our research grant proposal by the university gets accepted, then I'll have funding via university for 2 more years, so Potree would remain completely free.

**Comment by pierotofy** [comment]
Makes sense; I think Potree is an excellent software and you should be compensated for your efforts (even if it means leaning toward a proprietary license).

Then again, I would bet most companies would rather pay a license than to release the changes to their customized versions of Potree. That, combined with an annual subscription for support and perhaps the ability to vote on proposed changes/features might be all that it takes for companies to realize that there's value.

I would buy a subscription.

**Comment by josch** [comment]
> My beef is mostly with SAAS type monetization of Potree by companies that don't fund Potree in return. They don't need to change the converter source so AGPL doesn't do much, and since the monetization comes from the hosting service, making them release their customized version of Potree doesn't help fund future development of Potree. So I'm afraid AGPL won't really convince SAAS services to fund Potree.

Correct. There exists no free (as by OSI or FSF or DFSG definition) license that forces entities using your software without modifications to contribute anything back.

> Since there is uncertainty regarding my future employment at the university and therefore the future funding of Potree, I'll now have to find a way to convince companies to fund the ongoing development of Potree. And currently I'm leaning towards something like this:
> 
>     * Starting from version 2.0, Potree will be free for non-commercial and non-government use.
> 
>     * Government agencies and organizations that include Potree in a commercial product or service will need to acquirce a paid license.

That sounds sensible. I cannot be of any help in that regard but I hope you find a good license for that setup and that you will not have to engage into any legal battles with entities ignoring the license terms.

> That's what I'm leaning to right now. However, if our research grant proposal by the university gets accepted, then Potree will be funded via university for 2 more years, so Potree would remain completely free.

In our case, we are the robotics department at the university of würzburg and we are making our point clouds available online free of charge. Would we be having to pay a license fee because we are government funded or not (because we are not making money off Potree)?

Thank you for your amazing work -- you deserve to get paid for it.

**Comment by potree** [comment]
> In our case, we are the robotics department at the university of würzburg and we are making our point clouds available online free of charge. Would we be having to pay a license fee because we are government funded or not (because we are not making money off Potree)?

Public research and education would be exempt!

**Comment by dkastl** [comment]
Well, in my opinion the this license change will harm the project in the end. GPL or similar licenses are fine, but the key for contributions is a project that welcomes contributions not only of financial kind. With @martinheidegger we tried to do this, but it felt like community contributions were not appreciated. All this goes into the wrong direction in my opinion. However I understand the problem the license change wants to solve, but I don't think it will do so.

**Comment by potree** [comment]
> Well, in my opinion the this license change will harm the project in the end. 

That may very well be the case but since Donations and Contract work barely covered half-time work on Potree, it was either trying a paid license or dropping it entirely. 

>  the key for contributions is a project that welcomes contributions not only of financial kind.

The reason I'm not that keen about code contributions is that they also cause a lot of extra work that I have to validate and curate in my own free time.

**Comment by martinheidegger** [comment]
As I am referenced, I am feeling compelled to comment.

> With this, I'd hope to be able to switch to full-time development on Potree in the future.

I believe the point is that Daniel is trying to make is that in his experience your approach it is not going to solve your problem. Or in other words: your hopes seem to be misplaced _[1][2]_. But I am sure that there are a lot of other software projects out there that changed the license successfully and earned money with it. There are many experience reports on this online _[3]_.

My personal recommendation would be learning to cooperate and trust _someone_ that is more versed in community-management and selling software. Someone to take care of the financial and community parts of selling software. A partner doing things that you seem to not enjoy.

_Anyways: unwatching now, please don't reference me._

_[1]_ https://nodemailer.com/about/license/
_[2]_ https://medium.com/swlh/a-failed-effort-to-get-paid-for-an-open-source-project-bd7fa4658a1e
_[3]_ https://news.ycombinator.com/item?id=14446516
