### ISSUE TITLE
Adding geometry jitter in potree

### ISSUE THREAD

**Issue by WenBinPan** [potree/potree#822]
We use potree to add irregular geometry, using three.js According to the vertex coordinates, it is added successfully. But when the mouse is operated, the geometry will vibrate. How to solve this problem.

**Comment by midnight-dev** [comment]
> when the mouse is operated, the geometry will vibrate

Do you mean when dragging the camera around while holding down left or right click? Or does this happen every time the cursor is moved, even when not changing position/orientation? 

It would help if you could link to an example or provide a short GIF of this vibration.

**Comment by potree** [comment]
That's likely because of insufficient floating point precision. Javascript has double precision, but 3D models on the GPU only have float precision. If you want to store large coordinate values (~100k+) somewhat precisely, you'll need to transform them to the origin first.

Here is what you can do:
- Compute the minimum (or center) coordinate value of your geometry. Subtract this from all vertices before you store them into the Float32Array vertex buffer.
- Use the minimum (or center) coordinate as the position attribute of your three.js node.

**Comment by rsouthon** [comment]
@potree @m-schuetz could a similar approach be used to fix the problem with 32-bit floating-point precision loss of WebGL shaders? Specifically, when clipping boxes are used in point clouds with large coordinates, you can really see the problem. Can you point me in the right direction to a fix?
