### ISSUE TITLE
All Potree.org links redirected to Github

### ISSUE THREAD

**Issue by smcavoy12** [potree/potree#824]
Trying to view examples for reference, all potree.org links and example links are redirecting to https://github.com/potree/potree

**Comment by midnight-dev** [comment]
Pretty sure this is intentional for the time being. If you'd like to see the examples, you'll have to run them on your own for now. It's not that hard, but it requires a bit of prep. 

1. Install [node](https://nodejs.org/en/download/) - the LTS version is the one I've been using for months and it usually offers the best compatibility. Node will come with NPM, which is what will launch tasks like building the main script and running a local server. 

2. Download / clone the repository. If downloaded, extract the files into an easily accessible directory. 

3. Bring up a terminal or command prompt & navigate to the root folder of your files (typically inside the `potree` folder. 

4. Run `npm install` in the prompt. You should see it installing a bunch of packages. If there's an error, you may be in the wrong location or need to use elevated permissions. For Linux systems, `sudo npm install` may do the trick. Make sure `package.json` is in the path you're trying to install to. 

5. Run `npm run start`. Alternatively, if you have the folder open in VS Code, you can run the "start" task after using the terminal to install the dependencies. After a few seconds, you should have a local server running, which you can access with your browser at this URL: `http://localhost:1234` 

6. The examples will be found inside the "examples" directory. 

Hope this helps.

**Comment by smcavoy12** [comment]
@midnight-dev Thanks Ben, I'm running some of the examples on my server, but let's leave this up. Much appreciated!

**Comment by potree** [comment]
Thanks for the info. I only wanted to redirect the main page, not all examples and subpages. Will take a look at this.

**Comment by potree** [comment]
I've replaced the .htaccess redirection with a redirection in index.html. Only potree.org and potree.org/wp/showcase are now redirected to the github page. For the showcase, I'll need to create one directly on github or as a page that doesn't redirect.

**Comment by smcavoy12** [comment]
Much appreciated! Closing
