### ISSUE TITLE
Using Measurement tools on meshes

### ISSUE THREAD

**Issue by mikepianka** [potree/potree#838]
When meshes and shapefiles have been loaded into the view, mouse clicks do not register on them. Is there a way to use the measurement tools on these?

**Comment by m-schuetz** [comment]
Unfortunately there isn't, the measurement tools are all only developed for point clouds.

**Comment by plines** [comment]
It is possible to measure on shapefiles and other vector data.  I had to modify the code slightly to accomplish this. 
![image](https://user-images.githubusercontent.com/7026669/96746363-1945ed00-1395-11eb-99aa-76be4344ec1a.png)

**Comment by smcavoy12** [comment]
@plines 

Cool! Can I ask, are you exposing the vertices of the mesh, or raycasting on to the face surfaces?

**Comment by plines** [comment]
Honestly I don't recall, it's been years since I made that change.  I fixed a few things that didn't work as expected, like measure on shapefiles, fix the pointcloud tree to toggle children layers, etc.  I'd have to dig back in the code to find my solution, and this was also done on version 1.6 for reference.

**Comment by smcavoy12** [comment]
Ok, thanks! I'm glad to know it's doable at least.  Our crummy solution right now is to sample point clouds from meshes using CloudCompare. If we have other threejs loaders (not the PLY or OBJ loaders Markus included) in the same scene as a pointcloud it seems to block measurement tools for everything.

We've got the children layers for GLTFs now on 1.7.2, but we're finding that it increases loading time significantly.

**Comment by mikepianka** [comment]
@plines if you could find that code it would definitely be helpful. I have still been using 1.6 mainly. I would be happy to take a look into what it would take to bring that feature up to 1.7.

**Comment by plines** [comment]
I think I found it now, under static getMousePointCloudIntersection, change

**Comment by plines** [comment]
if(!point){
	continue;
}

let distance = camera.position.distanceTo(point.position);

**Comment by plines** [comment]
to this:
if(!point){
	if (intersects.length > 0){
		point = intersects[0].point;
		distance = intersects[0].distance;
	}
	else {
		continue;
	}
	//continue;
}
else{
	distance = camera.position.distanceTo(point.position);
}

//let distance = camera.position.distanceTo(point.position);

**Comment by plines** [comment]
If a pointcloud point is intersected, it takes priority.  But this logic will try to raycast to the scene's children, and use the first (closest) intersect if no pointcloud point is found.  As long as you add your vector data to the scene like this:
let shapeNode = new THREE.Object3D();
viewer.scene.scene.add(shapeNode);
the code above should work on vector data like shapefiles.  Another note, the shapefile reader used in potree doesn't read 3D shapefiles, so you'll need to set Z using an attribute instead of geometry.  Or do like I did and add a function to use geojson instead.

@m-schuetz I haven't looked at any of the viewers newer than 1.6, but you could incorporate the logic I added if you want to be able to measure things other than the points from the pointcloud.

**Comment by mikepianka** [comment]
@plines awesome, I will check that out. By the way, that issue with 3D shapefiles was a deficiency in the shapefile.js library, fixed here: [https://github.com/potree/potree/commit/424518b07ae3211a866b2ca518dacd3e35be6ef5#diff-f31067f65361dbe5e92806fc0e6c735213ee431e718e3578edbaaf5216256a13](url)

**Comment by mikepianka** [comment]
If anyone else gets an error about x being undefined it's because the coordinates are expected as a position attribute. Just add `point.position = point`

The full if block:

```
if (!point) {
	if (intersects.length > 0) {
		point = intersects[0].point;
		point.position = point;               // add position attribute
		distance = intersects[0].distance;
	} else {
		continue;
	}
} else {
	distance = camera.position.distanceTo(point.position);
}
```

**Comment by mikepianka** [comment]
Opened a PR here:
[https://github.com/potree/potree/pull/932](url)

**Comment by smcavoy12** [comment]
Jumping back into to this thread, when we implemented this code we had some odd behavior where it would only place a measurement on a mesh if there were a pointcloud behind it.
