### ISSUE TITLE
Is it(potree) possible to load html  without webserver?or start/stop webserver in QT?

### ISSUE THREAD

**Issue by Yes-Jumby** [potree/potree#844]
hi,everyone:
       I am going to using potree to show cloud in QT(ubuntu C++).I can show cloud now,only if I start up a websever before I start my Desktop APP of QT.I want to start the server and show up cloud in whole.
       **Highlight:**
       PLAN A:Setting potree to show cloud without webserver.
       PLAN B:start and stop a webserver in C++ QT .(i can use QT to start a live-server,but I cannot stop it)

anyone will give me a hand? Thanks.

**Comment by midnight-dev** [comment]
Modern browsers won't want to load the script resources / XHR locally for security reasons. However, these restrictions can be lifted in Firefox, and I can load Potree & point clouds locally without a server. I assume Chrome also has advanced settings that will allow this behavior. 

Despite the wishes of their email marketing team, I'm really not familiar with programming for the Qt platform. So I'm not sure what kind of browser is available nor what configurations it allows. If it's Gecko/Firefox based, there will be JavaScript files that can control its internal config. I'm not sure how/if a Chromium browser can be set to use custom advanced settings. 

If that leads to a dead end, what you may have to do is keep track of all child processes that your Qt application spawns, which should include a node process for the server. Whenever you want to shutdown the server, iterate through the handle names and signal or force kill anything named "node" ... But it would be much simpler if you could ask Qt to send a Ctrl-C input to the node CLI, as that's the quick, easy, and pretty clean way to end the server. By the way, make sure you're running the web server task rather than the build one. Build watches files for changes and recompiles the master Potree JS file on every change in addition to running a server.

If you're about to go with plan A, be sure to remove any address and search bars. If the user is able to navigate to an external page, like Google, they could come across a site that may use lowered restrictions to load rogue payloads which could result in stolen data. The risk is low, as browsers have had these restrictions enabled by default for years now, and a victim would have to be browsing some unsavory places to be attacked in the first place, but when you disable the restrictions there will always be some risk to you and anyone who uses such a browser. Hence, navigation should be disabled to reduce the risk.

**Comment by Yes-Jumby** [comment]
> Modern browsers won't want to load the script resources / XHR locally for security reasons. However, these restrictions can be lifted in Firefox, and I can load Potree & point clouds locally without a server. I assume Chrome also has advanced settings that will allow this behavior.
> 
> Despite the wishes of their email marketing team, I'm really not familiar with programming for the Qt platform. So I'm not sure what kind of browser is available nor what configurations it allows. If it's Gecko/Firefox based, there will be JavaScript files that can control its internal config. I'm not sure how/if a Chromium browser can be set to use custom advanced settings.
> 
> If that leads to a dead end, what you may have to do is keep track of all child processes that your Qt application spawns, which should include a node process for the server. Whenever you want to shutdown the server, iterate through the handle names and signal or force kill anything named "node" ... But it would be much simpler if you could ask Qt to send a Ctrl-C input to the node CLI, as that's the quick, easy, and pretty clean way to end the server. By the way, make sure you're running the web server task rather than the build one. Build watches files for changes and recompiles the master Potree JS file on every change in addition to running a server.
> 
> If you're about to go with plan A, be sure to remove any address and search bars. If the user is able to navigate to an external page, like Google, they could come across a site that may use lowered restrictions to load rogue payloads which could result in stolen data. The risk is low, as browsers have had these restrictions enabled by default for years now, and a victim would have to be browsing some unsavory places to be attacked in the first place, but when you disable the restrictions there will always be some risk to you and anyone who uses such a browser. Hence, navigation should be disabled to reduce the risk.

thanks,I have done it in PLAN B.I use Qt to send a Ctrl-C input to the node CLI(first,find pid by name,then send SIGINT to close the server).
Thanks a lot.

**Comment by midnight-dev** [comment]
Awesome possum 🎉 That's the safer option, too. Glad it worked. If you put your application on a USB drive or memory card, keep an eye on the available storage space, as the browser may want to cache the already (locally) stored point cloud resource files (i.e. the binary, LAS & LAZ files). It's negligible for tiny point clouds, though large ones can quickly eat up space. 

We could add an option to run strictly no-cache headers if it's needed. Might help with portable deployments where a small amount of file serving overhead is preferred instead of doubling the point cloud data. I'll throw it on the nice-to-have TODO list. 

Anyway, I appreciate the feedback. If everything is squared away, please close this issue so it's marked as resolved. You can still post additional comments to a closed issue to discuss details, and you can re-open the issue if the problem reappears under certain conditions. 
_(I'm sure you already knew that, but I'm putting this here to remind new visitors that they can comment on closed issues if they have questions.) _

By the by, how does the measurement and Potree file export work in the Qt program? Does it offer to save the JSON or navigate away? It may still allow for drag & drop events, which makes me wonder if it dynamically loads projects if a JSON file is dropped on it. That could be unexpected or unwanted behavior depending on the target audience. If Qt blocks that kind of action by default, you won't have to worry about it 👌

**Comment by Yes-Jumby** [comment]
> Awesome possum 🎉 That's the safer option, too. Glad it worked. If you put your application on a USB drive or memory card, keep an eye on the available storage space, as the browser may want to cache the already (locally) stored point cloud resource files (i.e. the binary, LAS & LAZ files). It's negligible for tiny point clouds, though large ones can quickly eat up space.
> 
> We could add an option to run strictly no-cache headers if it's needed. Might help with portable deployments where a small amount of file serving overhead is preferred instead of doubling the point cloud data. I'll throw it on the nice-to-have TODO list.
> 
> Anyway, I appreciate the feedback. If everything is squared away, please close this issue so it's marked as resolved. You can still post additional comments to a closed issue to discuss details, and you can re-open the issue if the problem reappears under certain conditions.
> (_I'm sure you already knew that, but I'm putting this here to remind new visitors that they can comment on closed issues if they have questions._)
> 
> By the by, how does the measurement and Potree file export work in the Qt program? Does it offer to save the JSON or navigate away? It may still allow for drag & drop events, which makes me wonder if it dynamically loads projects if a JSON file is dropped on it. That could be unexpected or unwanted behavior depending on the target audience. If Qt blocks that kind of action by default, you won't have to worry about it 👌

I use qwebengineview to display the html which can show pointcloud.when It is in ubuntu-x64,it works well;

when i use potree in ubuntu-arm64,it(potree.js) have a error:js :uncaught syntaxerror:unexpected token ).how could i solve this bug?
