### ISSUE TITLE
ARM64 problem using POTREE IN DESKTOPAPP:potree.js::uncaught syntaxerror:unexpected token )

### ISSUE THREAD

**Issue by Yes-Jumby** [potree/potree#847]
I have made a desktop app in ubuntu by qt using optree to display pointcloud in QWEBENGINEVIEW.when It is in ubuntu-x64,it works well;when i use potree in ubuntu-arm64,it(potree.js) have a error:js :uncaught syntaxerror:unexpected token ).Browser can display the html ,but QWEBENGINEVIEW display the html will have a bug in html (<script src="libs/potree/potree.js"></script>)
how could i solve this bug?

**Comment by midnight-dev** [comment]
So, here's the problem. When compiling a native program to use a browser to visualize 3D data like point clouds, the chain of dependencies gets pretty big. Getting this to work on x86_64 is beautiful, but there could be many factors that prevent use on arm64. I don't have any spare ARM devices I can use, so I'd have to emulate one just to test it. However, I'd also need every library and line of code that you're working with, and I'd need to have the same configurations, and then after all of that, I may not get the error you see because my emulation may not be exactly like your ARM platform. That would be a huge waste of time. But that does remind me that I should get an actual arm64 system that doesn't have a tightly locked bootloader. 

What I _can_ do is offer a possible cause. For a long while, reports have come in that iOS and Android systems (i.e. devices that use ARM) can't render Potree. Usually there's a crash, but it can sometimes manifest as a blank Potree page because the point cloud(s) just won't render. The fragment depth extension is unsupported on many ARM devices. Even if the hardware is modern and capable, I'm guessing mobile browsers are not built to support some WebGL features. So if this one extension within WebGL 1 can break Potree (1.x) on mobile, then the error you're seeing may be stemming from this. It could any other extension as well, like the one used for vertex arrays.

This is just speculation. Without having the exact setup or expert knowledge of the arm64 platform, I won't be able to give you an exact answer. That error is pretty generic. If the token it wasn't expecting was a closing parenthesis (literally "`)`") then something is breaking inside or just before a conditional or function call. And it doesn't help that there are no line numbers (like we'd normally see in Chrome or Firefox). Check to see if you can force the Qt web view to output line numbers on error & log console output to a file. Without that, it'll be very hard to nail down what your arm64 build is choking on. I still suspect an extension because ARM doesn't have the same instruction sets as x86, but I can't say for sure.

If it's the extensions that are causing problems and breaking the JavaScript, then you'll need to rewrite the scripts to not use any of those extensions. It will be a pain, but there's not much else you can do if that's the problem. I'd start with removing the fragment depth extension first. Recompile and see if it starts working for arm64.

I know you may need to translate this. Let me know if there's anything you want me to explain in a different way. It may help with translation.

**Comment by Yes-Jumby** [comment]
> So, here's the problem. When compiling a native program to use a browser to visualize 3D data like point clouds, the chain of dependencies gets pretty big. Getting this to work on x86_64 is beautiful, but there could be many factors that prevent use on arm64. I don't have any spare ARM devices I can use, so I'd have to emulate one just to test it. However, I'd also need every library and line of code that you're working with, and I'd need to have the same configurations, and then after all of that, I may not get the error you see because my emulation may not be exactly like your ARM platform. That would be a huge waste of time. But that does remind me that I should get an actual arm64 system that doesn't have a tightly locked bootloader.
> 
> What I _can_ do is offer a possible cause. For a long while, reports have come in that iOS and Android systems (i.e. devices that use ARM) can't render Potree. Usually there's a crash, but it can sometimes manifest as a blank Potree page because the point cloud(s) just won't render. The fragment depth extension is unsupported on many ARM devices. Even if the hardware is modern and capable, I'm guessing mobile browsers are not built to support some WebGL features. So if this one extension within WebGL 1 can break Potree (1.x) on mobile, then the error you're seeing may be stemming from this. It could any other extension as well, like the one used for vertex arrays.
> 
> This is just speculation. Without having the exact setup or expert knowledge of the arm64 platform, I won't be able to give you an exact answer. That error is pretty generic. If the token it wasn't expecting was a closing parenthesis (literally "`)`") then something is breaking inside or just before a conditional or function call. And it doesn't help that there are no line numbers (like we'd normally see in Chrome or Firefox). Check to see if you can force the Qt web view to output line numbers on error & log console output to a file. Without that, it'll be very hard to nail down what your arm64 build is choking on. I still suspect an extension because ARM doesn't have the same instruction sets as x86, but I can't say for sure.
> 
> If it's the extensions that are causing problems and breaking the JavaScript, then you'll need to rewrite the scripts to not use any of those extensions. It will be a pain, but there's not much else you can do if that's the problem. I'd start with removing the fragment depth extension first. Recompile and see if it starts working for arm64.
> 
> I know you may need to translate this. Let me know if there's anything you want me to explain in a different way. It may help with translation.

I have rar the potreecloud \libs\html in PotreeCloud ,DesktopAPP in Qwebengine ,here is the rar file named Potree_ARM64.
attention: 
QT should be 5.4 or higher to have the QWEBENGINE
QT install may be this :
sudo apt-get install qt5-default qtcreator -y // install the QT main program
sudo  apt-get install qtwebengine5-dev//install moudule qtwebengine to use webengine
plus: OS-ubuntu 18.04LTS 

here is the link to download the rar files:
link：https://pan.baidu.com/s/1ieRpB91NnnimCPTQ5Tu13A 
password：c23q

may it will help you to find and fix this problem.If any question,please reply me.Thanks a lot.

**Comment by midnight-dev** [comment]
Sorry mate, I'm just not going to have time for it right now. I still have a lot of work on my backlog.

Remember, I **do not** have an ARM device I can develop on, and emulating **may not** show the same error.

If you want someone to help with this, please use a cloud client that is accessible to the wider internet. Not sure if anyone else will have this issue, but I cannot connect to pan.baidu.com... I even tried accessing it from Japan with no luck. Maybe it's China-only?

Best of luck.

**Comment by Yes-Jumby** [comment]
> Sorry mate, I'm just not going to have time for it right now. I still have a lot of work on my backlog.
> 
> Remember, I **do not** have an ARM device I can develop on, and emulating **may not** show the same error.
> 
> If you want someone to help with this, please use a cloud client that is accessible to the wider internet. Not sure if anyone else will have this issue, but I cannot connect to pan.baidu.com... I even tried accessing it from Japan with no luck. Maybe it's China-only?
> 
> Best of luck.
yes, I see.look forward to see your test result once you have time to test. Thanks

I had upload the rar files in github.I think it will be a best solution.
link:git clone https://github.com/Yes-Jumby/potree_ARM64

**Comment by Yes-Jumby** [comment]
> Sorry mate, I'm just not going to have time for it right now. I still have a lot of work on my backlog.
> 
> Remember, I **do not** have an ARM device I can develop on, and emulating **may not** show the same error.
> 
> If you want someone to help with this, please use a cloud client that is accessible to the wider internet. Not sure if anyone else will have this issue, but I cannot connect to pan.baidu.com... I even tried accessing it from Japan with no luck. Maybe it's China-only?
> 
> Best of luck.

is there any General planning about this bug？

**Comment by m-schuetz** [comment]
> is there any General planning about this bug？rough time plannning on date？

Unfortunately I don't have ARM devices and little experience with linux development, so I won't be able to work on it. If you find a solution that's not too tough to integrate, you could open a PR and I will merge it.
