### ISSUE TITLE
License Draft

### ISSUE THREAD

**Issue by m-schuetz** [potree/potree#861]
Draft for a license for the new PotreeConverter. Please share your thoughts and suggestions. Source and windows binaries for the new converter will be uploaded in the next few days under this license.

Note that Potree 1.7 and PotreeConverter 1.7 remain free and Open Source under the BSD 2 clause license. This draft is only about PotreeConverter 2.0, which is a complete rewrite from scratch. 

# License 
``` 
========================
== Potree Converter 
========================

http://potree.org
https://github.com/potree/PotreeConverter

Copyright (c) 2011-2020, Markus Schütz
All rights reserved.

Contact: licensing@potree.org

PotreeConverter comprises a free and a paid part.

1. Non-commercial and non-government users may use and modify the 
source code and binaries for free.
This includes universities and research institutions as long as the 
application is not used for or part of a commercial product or service.
2. Commercial and government users may use and modify the 
source code and binaries after purchasing a commercial license. 
3. Commercial and government users may use PotreeConverer 
for free for three months, before deciding whether to purchase a license. 
4. Paid licenses are per simultaneously running instance. A single license 
may be used to install PotreeConverter on multiple devices of the licensee, 
as long as only one instance runs at a time. 
5. Anyone may redistribute source, binaries, and modifications of either, but 
redistributions and modifications must retain this LICENSE file and recipients 
are also subject to its conditions. The recipients must be made aware of the 
license conditions. If the recipient is a commercial or government user, 
then the recipient must also purchase a license. 

Exceptions: If you feel that the terms above don't fit your use case or that you 
can't afford a paid license for your project (e.g., art, indie, ...), 
feel free to inquire for different terms or exceptions at licensing@potree.org. 
Note that the first three months are free in any case. 

For questions and clarifications, please contact licensing@potree.org.
```

# Pricing

Licenses are per simultaneously running instance of PotreeConverter 2.0. The licensee can install PotreeConverter on multiple devices of the licensee, but only keep one instance of the converter running at a time. 

1. 240€ per instance for a perpetual license of the software at the date of purchase, plus one year of updates. 
2. 2400€ per instance for fully automated SaaS hosting services that include PotreeConverter. This applies to online services that provide customers a platform to upload their data, which is then automatically processed by a converter instance, and finally made available online publicly or behind authentication (e.g. youtube or sketchfab for point clouds). 
3. Anyone who has donated to or funded Potree before August 2020 is considered to have a perpetual license under bullet point [1], plus additional instances of [1] or [2] that match the amount of donation/funding. 

* Note that this only applies to the licensee using PotreeConverter 2.0. You're allowed to convert your customers data with PotreeConverter 2.0 and host it online via Potree 1.7(free), without the need to aquire additional licenses for customers. You're also allowed to ship converted data via PotreeDesktop 1.7 without the need for additional licenses. The customer will only need to purchase licenses if they decide to convert point cloud data with the converter themselves. 
* If in doubt, just start using it for the three month trial period and ask for clarifications via licensing@potree.org
* Licensees will have priority support. I'll resolve smaller issues as fast as possible, and offer support plans for larger issues. 

# Changes

* Added "Exceptions", notifying users that they may inquire for exceptions. 
* Updated to cover multi-user multi-license cases. License is per simultaneously running instance. A licensee may use a single license to install the software on all of the licensee's devices, but needs additional licenses for each simultaneously running instance.

**Comment by m-schuetz** [comment]
It'll be open source, of course, and there will be no license servers that degrade the user experience.

**Comment by tentone** [comment]
I would recommend having somebody with legal knowledge take a look into the license since the meaning of "commercial work" can be troublesome. Also would be a good idea to properly define the starting point for the three-month trial usage of the library.

Appreciate all the work you have been doing with potree.

**Comment by afr-git** [comment]
If the perpetual license includes one year of updates, does that mean there will need to be a separate maintenance/support contract to receive updates beyond that?

**Comment by potree** [comment]
> If the perpetual license includes one year of updates, does that mean there will need to be a separate maintenance/support contract to receive updates beyond that?

The thinking was that I don't want to limit a license by time, whatever you buy should be yours to use forever, but I also need funding for continuously working on Potree. So if you want to have the latest version you'll have to pay for updates outside of the included year. E.g., you could set up a yearly 240€ donation via github (altough github does it monthly so 20€/month).

**Comment by potree** [comment]
Will modify pricing to include "any donor or funder before august 2020 receives a perpetual license under [1], plus instances of [1] or [2] matching the amount of their previous funding.

**Comment by potree** [comment]
> My only concern (and this also applies to the cc-nc licence) is the definition of "commercial". I worry that 0/no-budget arty or indie projects might not count as commercial but might not be able to afford those fees. Is there a standard definition of "non-commercial" anywhere?

@andybak raised concern about no-budget projects that may be considered "commercial" but don't really have the means to pay for a license. 

https://twitter.com/andybak/status/1290308576813015040

Offer exceptions on request?

**Comment by LFraser** [comment]
Will purchasing a license include a specific number of hours for support or feature requests?

**Comment by HeadLessHUN** [comment]
Hi there!

We are a civil engineering company, which uses potree to visualise buildings point clouds for modeling, and other tasks, and of course we give the Potree desktop viewer alongside the real work (2d drawings, and 3D models) to our customer so they can view the original point clouds and images as well. In this case how will the license will applied? Is it only a one time license for our use or every customers needs to buy a license?

**Comment by potree** [comment]
> Will purchasing a license include a specific number of hours for support or feature requests?

@LFraser no, not at that price point. It's intended to fund core Potree development, including features that I'd like to include myself and fixing serious bugs. Since you're a github donor, you'd already have a license btw. 

> And how do you plan to restrict for example trial versions or updates without license server?

It's on a trust basis. Including a license server would seriously degrade user experience for anyone, and also not work very well for free/non-commercial users. It'd also be a lot of work that doesn't actually do anything to improve Potree.

> Inside our office there are several architect, modeller. And we run potre on a regular webserver, so every one of them can use, see the different pointclouds which they work on. How many license should we buy is it only a converter or viewer based license?

It only applies to PotreeConverter 2.0 for now, the viewer and converter version 1.7 are still free. I'll have to think about how to handle amount of licenses needed.

> In this case how will the license will applied? Is it only a one time license for our use or every customers needs to buy a license?

Good question, just for viewing purposes, you wouldn't need additional licenses so if you distribute converted models with PotreeDesktop, then no additional licenses are needed. If the customer would want to convert their own point cloud with the new converter, then they'd also need to acquire a license. 

Next update of PotreeDesktop will be able to load the new format. For the purpose of converting point clouds by drag&drop into PotreeDesktop, I'll add an option to choose between the old and fully free converter or the new one that requires a license.

**Comment by afr-git** [comment]
> > If the perpetual license includes one year of updates, does that mean there will need to be a separate maintenance/support contract to receive updates beyond that?
> 
> The thinking was that I don't want to limit a license by time, whatever you buy should be yours to use forever, but I also need funding for continuously working on Potree. So if you want to have the latest version you'll have to pay for updates outside of the included year. E.g., you could set up a yearly 240€ donation via github (altough github does it monthly so 20€/month).

Thank you, I had meant to say in my original comment but I appreciate the work you've put in to developing all of this! Potree is an incredible resource. I don't know if the pricing you've listed here is just illustrative or finalised, but I agree with other comments and think it is certainly reasonable. I also don't know if this is a helpful suggestion, but a couple of models I've noticed with regards to supporting users for updates and future versions could also include (a) time based, e.g. an annually renewed maintenance 'contract' in addition to the lifetime license purchase, but which is typically priced lower than upfront lifetime license cost and includes all minor & major version upgrades if annual payment is maintained, and/or (b) the purchase of a lifetime license includes upgrades for all minor version increments (features and bug fixes) e.g. v2.x, but would not include major upgrades to 3.x, 4.x, etc. So a new 'lifetime license' would need to be purchased for major upgrades. This would remove the need to track 1yr duration for lifetime license purchases without maintenance.

> > My only concern (and this also applies to the cc-nc licence) is the definition of "commercial". I worry that 0/no-budget arty or indie projects might not count as commercial but might not be able to afford those fees. Is there a standard definition of "non-commercial" anywhere?
> 
> @andybak raised concern about no-budget indie/art projects that may be considered "commercial" but don't really have the means to pay for a license.
> 
> https://twitter.com/andybak/status/1290308576813015040
> 
> Offer exceptions on request?

Just a thought on this - perhaps if you anticipate a lot of these requests that you will need to vet/approve this could be quite involved? I've seen 'commercial use' software offered for free based a revenue threshold, e.g. if your company earns under $$$ per year then might qualify for free, or reduced indie rates.

**Comment by HeadLessHUN** [comment]
> > In this case how will the license will applied? Is it only a one time license for our use or every customers needs to buy a license?
> 
> Good question, just for viewing purposes, you wouldn't need additional licenses so if you distribute converted models with PotreeDesktop, then no additional licenses are needed. If the customer would want to convert their own point cloud with the new converter, then they'd also need to acquire a license.

So it is more like a converter license. We normally convert our pointclouds one time and share the converted cloud inside our company (read only) and to our client (desktop). So it is not a service where they can convert themself. It means that we would only need a normal [1] type license to convert our clouds and then we can distribute the converted clouds?

We don't use drag and drop as in dekstop viewer, we always create a fixed index.html to every project, so our client doesn't have to load every time they open it.

**Comment by midnight-dev** [comment]
I like it. Without naming any names, there are a few large corporations that use Potree who go to extra lengths to remove all attribution and copyright data. Some of them bring in over $1,000,000 in revenue on a yearly basis. Would you really be okay with those entities using the new major version in the same way for only €240 per year?

By the way, to add additional value, you could open up a private forum where subscribers could go to for support. I believe this would encourage more people to subscribe even during periods where they don't suspect a new version may be released. Then again, this sort of thing requires regular attention, so if it gets too active, productivity may slow down.

**Comment by m-schuetz** [comment]
> @midnight-dev Would you really be okay with those entities using the new major version in the same way for only €240 per year?

> @HeadLessHUN  How many license should we buy is it only a converter or viewer based license?

I've added ```Paid licenses are per simultaneously running instance```. This should scale better with the size of the company and it still allows users to install the converter on multiple devices with a single license, as long as they only spawn one instance at a time. I'll add a volume discount to the pricing, though. 

> @midnight-dev By the way, to add additional value, you could open up a private forum where subscribers could go to for support.

> @LFraser Will purchasing a license include a specific number of hours for support or feature requests?

Not going to make a private forum or hours of support, but I could add a guarantee that I'll reply on emails to quickly help with smaller issues and potentially setup a support plan to resolve larger issues.

**Comment by midnight-dev** [comment]
@m-schuetz "Priority support" is a popular buzzword for subscriptions 👌

**Comment by HeadLessHUN** [comment]
> I've added `Paid licenses are per simultaneously running instance`. This should scale better with the size of the company and it still allows users to install the converter on multiple devices with a single license, as long as they only spawn one instance at a time. I'll add a volume discount to the pricing, though.

But will restrict paralellizations in scripts. usually run 8-10 paralell thread because we use a lot of smaller chunks of cloud  to be able filter points by scan location. and of course it is so much faster to convert then a huge cloud. Of course if there will be some optimization/paralellization in the convert process it will eliminate the need of paralellized scriptings.



> @m-schuetz "Priority support" is a popular buzzword for subscriptions

it is easier to sold that way... :+1:

**Comment by m-schuetz** [comment]
> But will restrict paralellizations in scripts. usually run 8-10 paralell thread because we use a lot of smaller chunks of cloud to be able filter points by scan location. and of course it is so much faster to convert then a huge cloud. Of course if there will be some optimization/paralellization in the convert process it will eliminate the need of paralellized scriptings.

The new converter is heavily parallelized. If the source files are in laz format and if you're using an SSD, CPU usage will be 100% most of the time. Do you have a suggestion that you think might be balanced for a single user with multiple devices, but also companies that could process tens or hundreds of files simultaneously on a cloud platform?

**Comment by HeadLessHUN** [comment]
> The new converter is heavily parallelized. If the source files are in laz format and if you're using an SSD, CPU usage will be 100% most of the time. Do you have a suggestion that you think might be balanced for a single user with multiple devices, but also companies that could process tens or hundreds of data sets simultaneously on a cloud platform?
> 
> >

In that case if it is really paralellized than there is no need for multiple running instance for our use. But if it is not than i suppose a higher priced server license would be ideal with hardware lock (for example mac address lock).

For example if there is different numa nodes then you can only scale it to one node. Or if we talk about cloud computions where there is a need of different jobs to be done, so there is a need for multiple instance and they won't know how many instances they will use. In these last case the only way is hardware locked license, with unlimited (or fairly high) instance.

**Comment by m-schuetz** [comment]
@HeadLessHUN 

> In that case if it is really paralellized than there is no need for multiple running instance for our use. 

In my benchmarks, the new converter was consistently around 10-50 times faster than PotreeConverter 1.7, so that hopefully alleviates this issue. I'll go with the "per instance" wording initially but if you find that it doesn't work all that well for you, feel free to contact me to discuss different licensing terms. 

![image](https://user-images.githubusercontent.com/6705073/89299429-ec701c80-d666-11ea-95c8-4d55725d9981.png)
( Poisson and Random are the two sampling options of the new converter)

**Comment by smcavoy12** [comment]
I'd just like to say that I think this license plan is generously priced. I deal with a lot of well funded University research labs routinely paying $10,000-$20,000 for single seat node locked lidar/sonar/microscopy visualization software that isn't anywhere near as smooth as potree. I'm almost sad that they'll be getting it for free, knowing they could throw money at it. I'll be sure to push the 250€ license with them anyway. Thanks for all you do, VERY excited about the new converter.

**Comment by jo-chemla** [comment]
+1 for the details of the licensing presented in the readme of converter 2.0, and separation of automated processing instances vs manual ones - also it is probably true that some businesses or public institutions could afford more depending on their revenue. 

As a side-note related to your table, do you know how much of the speed increase of the new converter is due to multi-core vs single-core and how much is due to the rewrite? And how many cores has the machines on which the tests were run? And again, thanks a lot for the hard work!

**Comment by m-schuetz** [comment]
> @jo-chemla As a side-note related to your table, do you know how much of the speed increase of the new converter is due to multi-core vs single-core and how much is due to the rewrite? And how many cores has the machines on which the tests were run? And again, thanks a lot for the hard work!

The test machine was using an AMD Ryzen 2700X with 8 cores / 16 threads. Performance improvements are a combination of more cache and IO friendly data processing and parallelization. The old PotreeConverter was only using a single core for indexing, the new one is all about splitting works into smaller batches that can be indexed in parallel. I'm just now finalizing the paper preprint that has more detailed explanation of the new converter.

> @jo-chemla also it is probably true that some businesses or public institutions could afford more depending on their revenue.

> @smcavoy12 I'm almost sad that they'll be getting it for free, knowing they could throw money at it. 

Yeah, I think so too, but it's a bit hard to find a balance that also keeps it affordable. Let's see how it plays out and if it doesn't work, the license might have to be adjusted in the future.

**Comment by geoff-harper** [comment]
> This draft is only about PotreeConverter 2.0, which is a complete rewrite from scratch.

What are the licensing plans, if any, for client side Potree? Will we be seeing something similar in the near future? I'm using a fork of Potree in a commerical product and fall pretty squarely into "SaaS type monetization of Potree by companies that don't fund Potree in return", so I have a vested interest in this. I believe my company would have no problem with the pricing you listed but frankly we went with the fork instead because of numerous code quality improvements like decoupling UI (no SaaS wants the Potree UI), Typescript, and modularization. If this was all rectified in a grand 2.0 release and could be packaged alongside Converter 2.0 it would be very enticing to us. As it stands however, there just isn't enough value and I suspect the big players using Potree that I'm sure you're aware of will feel similarly.

**Comment by potree** [comment]
> What are the licensing plans, if any, for client side Potree? Will we be seeing something similar in the near future?

The WebGL based version will stay under the bsd 2-clause license but in the future I plan to work on a complete rewrite from scratch (just like the converter) to take advantage of the new WebGPU API. This rewrite may or may not follow the same or similar licensing, or perhabs remain free with only the converter being paid for commercial use. Nothing is decided yet, and it will probably take 6-12 months until the first release of Potree 2.0. 

>  I'm using a fork of Potree in a commerical product and fall pretty squarely into "SaaS type monetization of Potree by companies that don't fund Potree in return", so I have a vested interest in this. I believe my company would have no problem with the pricing you listed but frankly we went with the fork instead because of numerous code quality improvements like decoupling UI (no SaaS wants the Potree UI), Typescript, and modularization. If this was all rectified in a grand 2.0 release and could be packaged alongside Converter 2.0 it would be very enticing to us. As it stands however, there just isn't enough value and I suspect the big players using Potree that I'm sure you're aware of will feel **similarly.**

That's understandable but the things you list aren't in Potree because they add additional implementation and maintenance overhead that aren't fun to do, of no particular use to myself, and not funded by most those that would benefit from it (with some exceptions that did fund Potree and would benefit from it, but other features had priority). Typescript probably won't be used because I prefer instant change to execution and debugging of modified code, which is also why I'm tending to using bare ES6 at first, with an optional choice of a packaging build later on. Decoupling UI may or may not happen, depending on the amount of effort needed and whetever the new PotreeConverter 2.0 license can actually support full-time development on Potree. 

> As it stands however, there just isn't enough value

It seems like there are quite a few companies out there that have the impression that there is enough value to monetize Potree as long as they don't have to fund the development of Potree and even discard any trace of Potree entirely The latter is really my main issue - after all I'm also relying on free third party libs to get things done. In any case, I do want to turn it into a great library and application and I wish I could keep it free, but current funding runs out and I need a source of income. I'd like to continue working on Potree and perhabs even go from turning Potree from a side project into a full-time project.

**Comment by potree** [comment]
Closing this now since [PotreeConverter 2.0](https://github.com/potree/PotreeConverter) is out with the new license, but everyone is free to continue to post thougts/concerns/suggestions in this thread.

**Comment by geoff-harper** [comment]
Hey thanks for taking the time to reply. 

> That's understandable but the things you list aren't in Potree because they add additional implementation and maintenance overhead that aren't fun to do, of no particular use to myself, and not funded by most those that would benefit from it

Based on the users of the fork that does have these modern features, there's absolutely an appetite for it. That being said, at least for us, getting a SaaS license before there's progress or concrete plans for these things that are required would be putting the carriage before the horse. 

> Typescript probably won't be used because I prefer instant change to execution and debugging of modified code, which is also why I'm tending to using bare ES6 at first, with an optional choice of a packaging build later on. Decoupling UI may or may not happen,

Understandable for TS, `@types` can step in for that. The real non-starters for myself are the UI and lack of code splitting.

At the end of the day, what Potree does within it's environment is great  and it's the best option that I've been able to find. We'd love to see it succeed and get to a place where we can justify putting money into it as a product.
