### ISSUE TITLE
npm install failing on linux

### ISSUE THREAD

**Issue by jamesNWT** [potree/potree#881]
Hello, I was following the "getting started" section, and I have immediately run into an error. Context: cloned the repo, installed nodejs and npm, and tried `npm install`. I am new to node and npm.

Here is the console output:
[errortext.txt](https://github.com/potree/potree/files/5170869/errortext.txt)

I have also attached the log file as directed
[npm-debug.log](https://github.com/potree/potree/files/5170865/npm-debug.log)

**Comment by potree** [comment]
```npm ERR! node v8.10.0```

Are you using node version 8? If so, you might have to update to a later/the latest one.

**Comment by midnight-dev** [comment]
Hi James. I noticed a snap path reference in one of the logs provided. Does this mean you're running Ubuntu? Latest version?

It's unfortunate that many Debian flavor distributions insist on keeping an ancient version of Node in their system repositories, but there was an upstream incompatibility with a dependency. It was resolved in some repos while others left everything untouched to keep downstream dependencies unaffected. I'm sure there are other flavors that have old versions, but Debian, Ubuntu, and Mint were the major offenders if I recall correctly.

If you need assistance, I can refer you to instructions on getting a recent LTS or stable version installed which won't break dependencies with existing packages. Probably should lay out some basic instructions in the readme anyway. The issue is that there are so many distros and versions of Linux. It's not always necessary or wise to take additional steps for a non-default installation.

**Comment by jamesNWT** [comment]
Thanks for the replies, I do indeed have node 8.10. I've been trying to update it, so I just installed nvm, which isn't working smoothly either (feeling like a noob). I will update when I get a new version of node installed.

**Comment by midnight-dev** [comment]
Can you confirm what distro of Linux you're using and what version it is?

**Comment by jamesNWT** [comment]
Ubuntu 18.04.5 LTS

**Comment by jamesNWT** [comment]
Well, I was able to fix this and install potree and start it. 

I used nvm to install the latest LTS of Node, and after that it worked just fine.

The reason nvm wasn't "working smoothly" was because for some reason my curl package wasn't supporting https, I ended up having to download curl source and installing it with SSL (whatever that is). 

Thanks for the help both of you!

**Comment by midnight-dev** [comment]
Thanks for the information, James. We'll have an easy reference for other Ubuntu 18 users facing this issue now. I've updated the readme information for Linux users in PR #882
