### ISSUE TITLE
tween between two sets of points

### ISSUE THREAD

**Issue by kittles** [potree/potree#883]
i may be a little premature in asking this, as im new to point cloud vis, but it would be perfect for something im working on to be able to tween between two pointclouds- in my case i have 2 3d datasets that id like to animate the change between. just figured id ask if there is something out of the box or close to it for that- otherwise its perfectly ok for me to make something by hand. thanks!

**Comment by smcavoy12** [comment]
We'd made a simple frame by frame animation setup, playing 10 point clouds one after another, each flipped visible for 0.1 seconds. 

Not as easy as tweening, but I guess you could put incremental transfoms in, e.pointcloud.(scale or position or rotation).set,  have it swap in a more drastic transform at each frame. 

Different pointclouds as different frames is pretty stuttery outside of our network, I'm sure there's a way to load a pointcloud into memory without loading making it visible, applying some kind of clipping volume mask selectively.

});

			Potree.loadPointCloud("pointclouds/frame1/cloud.js", "frame1", e => {
			let pointcloud = e.pointcloud;
			let material = pointcloud.material;
			viewer.scene.addPointCloud(pointcloud);
			material.activeAttributeName = "RGBA";   
			material.size = 1;
			material.pointSizeType = Potree.PointSizeType.ADAPTIVE;
			material.shape = Potree.PointShape.SQUARE;
			viewer.fitToScreen();
	
			setInterval(function(){
			e.pointcloud.visible = false
			}, 100);
			
			setInterval(function(){
			setTimeout(function(){e.pointcloud.visible = true}, 0);
			}, 1000);
		
		});
		
			Potree.loadPointCloud("pointclouds/frame2/cloud.js", "frame2", e => {
			let pointcloud = e.pointcloud;
			let material = pointcloud.material;
			viewer.scene.addPointCloud(pointcloud);
			material.activeAttributeName = "rgba";  
			material.size = 1;
			material.pointSizeType = Potree.PointSizeType.ADAPTIVE;
			material.shape = Potree.PointShape.SQUARE;
			viewer.fitToScreen();
	
			setInterval(function(){
			e.pointcloud.visible = false
			}, 100);
			
			setInterval(function(){
			setTimeout(function(){e.pointcloud.visible = true}, 100);
			}, 1000);
		
			
		});
			Potree.loadPointCloud("pointclouds/frame3/cloud.js", "frame3", e => {
			let pointcloud = e.pointcloud;
			let material = pointcloud.material;
			viewer.scene.addPointCloud(pointcloud);
			material.activeAttributeName = "rgba";    
			material.size = 1;
			material.pointSizeType = Potree.PointSizeType.ADAPTIVE;
			material.shape = Potree.PointShape.SQUARE;
			viewer.fitToScreen();
	
			setInterval(function(){
			e.pointcloud.visible = false
			}, 100);
			
			setInterval(function(){
			setTimeout(function(){e.pointcloud.visible = true}, 200);
			}, 1000);
		
		});
And so on`

**Comment by midnight-dev** [comment]
> it would be perfect for something im working on to be able to tween between two pointclouds- in my case i have 2 3d datasets that id like to animate the change between. 

That sure would be spiffy, but I'm not sure it's feasible. There's no good way to identify which points should be tied to the points of another cloud. It might be easy for humans to recognize areas of separate point clouds and imagine a change over time, but these point clouds are just spatial points with attributes like color. Even scanning the same target with the same equipment and converting to LAS with the same settings, I'm doubtful you'd find a quick algorithm to reliably match points between two LAS files.

Think of it like this. You get two pictures of ~100 marbles and you must reconstruct the movement of the marbles between the images. The marbles in each picture are bunched up in a circle with a small amount of random space between each ball. In a respective ratio of 10% : 40% : 50%, some of them are unique, some of them are similar in appearance, and the rest look identical. Even if the marbles had been violently mixed after their state was first recorded, you could easily make connections among the marbles that are completely unique from all of the others and only changed their location, but that would be about it. _All_ of the other marbles with look very similar or identical to their neighbors. So how can you draw the path of movement between the two states of the marbles when they just look like a bunch of balls in different places with no discernable order? 

The analogy isn't perfect, but the thing is that there is no absolute reference that you could use to tie separate points together across two states (or point clouds). Maybe scan order if you were very careful and had exacting precision from start to finish. I think tween could still be used if you were applying an algorithmic transformation on a point cloud, but I'm still skeptical if it can be used to animate changes between two point clouds. That sounds like the kind of thing you'd want deep learning feature detection for. 

I struggle to imagine how tweening points in an octree would even work. Would a point hop from bounding box to bounding box as it travels? But maybe it could just be visually distorted instead of modifying the octree geometry. I could be way off. Perhaps Markus or one of his research mates knows of a novel way to achieve this. I have to admit, it would be neat to see points flying around as if they were unbound particle effects.

For something simple and effective, I have to second Scott's method of pseudo animation by ticking through point clouds. You may need to tweak the interval and number of clouds before the effect becomes convincing. And if this turns out to be the only way, you may want to perform more incremental scans to show smoother progress - assuming you're running regular LiDAR scans.

**Comment by kittles** [comment]
in my case the x-y coordinate pair can be used to correlate points between two data sets

**Comment by smcavoy12** [comment]
We'd  briefly explored the idea of setting up a 3D grid point cloud, where each point has a color value associated with a particular time, so you would have each point switching different color values at different times, kind of like pixels on a screen. Points without a color value at a given time would be transparent. We haven't worked out that a data structure for that yet, but it seems possible and much better than a frame by frame loading of different pointclouds. 

I'd bet there's a way to what you want with Maya's Bifrost, but for Potree integration (as I understand it) you'd still have to export it frame by frame or else the entire Octree structure would have to be recalculated as points move from one node to another. There are some interesting talks about the limitations of voxel structures in game engines that applies here (I think).
