### ISSUE TITLE
IPhone can't view point cloud

### ISSUE THREAD

**Issue by Paweled** [potree/potree#890]
I downloaded the latest version of potree 1.7. I can see the point cloud on my computer and Android phone, but I can't see the point cloud on my iPhone.

**Comment by midnight-dev** [comment]
Try disabling Eye Dome Lighting.

**Comment by Paweled** [comment]
I've disabled it viewer.setEDLEnabled (false);

I tried multiple browsers on my computer and found only Google and Firefox were available;

The following similar error occurred on iPhone:
![image](https://user-images.githubusercontent.com/45220025/93313328-ec089b00-f83a-11ea-89fa-88511b95e61c.png)

**Comment by m-schuetz** [comment]
Safari isn't supported because it's usually way behind Firefox and Chrome. In this case, it looks like Safari doesn't support numeric literals, which is what causes this error. You can try to remove the numeric literals, e.g. turn "1_000_000" into "1000000", or you could try to use babel to translate Potree into older javascript versions.

**Comment by m-schuetz** [comment]
Actually, Safari is supposed to support them. What version of Safari do you use? Also, as far as I know there is no real Firefox or Chrome on iphone, they're mostly reskins.

![image](https://user-images.githubusercontent.com/6705073/93313826-425ce600-f809-11ea-9239-ce9e16d5e1ff.png)

**Comment by Paweled** [comment]
I use iPhone, Chrome browser (85); loading error "potree 'is not defined";

I used multiple browsers on the iPhone to test that it didn't load successfully

**Comment by m-schuetz** [comment]
According to [this stackoverflow post](https://stackoverflow.com/questions/49890333/is-the-js-engine-on-ios-or-maxoss-chrome-browser-v8or-javascriptcode), Chrome on ios is essentially a reskined Safari. Same rendering engine, same javascript engine, same errors.

**Comment by Paweled** [comment]
I found that after modifying the source code here, it can be displayed (remove n). What does "1n" and "0n" mean and how to change it
![image](https://user-images.githubusercontent.com/45220025/93327649-36931300-f84d-11ea-94de-cddc2149df7b.png)

**Comment by m-schuetz** [comment]
The n makes it a BigInteger number. This was done because [byteOffset and byteSize are BigIntegers](https://github.com/potree/potree/blob/57f71cc265382c6a45727cadf2e1e31f40afee92/src/modules/Loader_1.8/OctreeLoader_1_8.js#L146-L147) and as far as I remember I got errors when I subtracted a normal Number from a BigInteger. You might want to check if all browsers accept your change to remove the n.

**Comment by m-schuetz** [comment]
BigInt support is coming to Safari with version 14. This is going to be important because the compressed Potree format will also use BigInt. 

![image](https://user-images.githubusercontent.com/6705073/93341464-6f6fbf80-f82e-11ea-879a-5931da62f565.png)
