### ISSUE TITLE
v1.7 measurements error - THREE.LineGeometry is not a constructor

### ISSUE THREAD

**Issue by ntr-808** [potree/potree#896]
When trying to add a measurement:

```
Uncaught TypeError: THREE.LineGeometry is not a constructor
    createHeightLine Measure.js:6
    Measure Measure.js:308
    startInsertion MeasuringTool.js:150
    initToolbar sidebar.js:109
    jQuery 2
```

Grave demo site reproduces this:
http://potree.org/potree/examples/showcase/grab_15.html

The three.js line API appears to have changed:
https://threejs.org/docs/#manual/en/introduction/Drawing-lines

**Comment by midnight-dev** [comment]
This is due to the showcase examples being a bit out of date. Working examples can be found within `/examples/` but outside of `/examples/showcase/` ... This is a standing issue that can be resolved by updating the HTML files in that directory. You just have to add the ThreeJS "extra" lines JavaScript after the three.js script tag. Also worth mentioning is that the `potree.org/potree/...` examples are using an older version 1.6 instead of the newer 1.7.

Hope this helped.

**Comment by ntr-808** [comment]
thanks @midnight-dev
