### ISSUE TITLE
Broken : dbltap on device mobile to make zoomToLocation()

### ISSUE THREAD

**Issue by loicroybon** [potree/potree#910]
Hello, 

I'm trying to add dbltap event on device mobile to use zoomToLocation() function. I did that on a previous version of Potree but on 1.7.2 it produce an "Potree Encounterd An Error" error.

Emulated touche device on Chrome devtools works, but on a real touch device (Hauwei phone using Chrome) this error occurs.

Any idea ?

Thanks

**Comment by smcavoy12** [comment]
Just adding on, we get this same behavior on very old PCs, yesterday we tested with a 2008 Dell 330 running windows 7.

**Comment by Paweled** [comment]
I have a similar problem;

The possible reason is: the mobile terminal does not support it material.shape = Potree.PointShape.PARABOLOID ;



Because I used the pick method, and in version 1.7 pick uses (parabolid) by default.

I modify the pick here, the mobile terminal can be used normally;
![image](https://user-images.githubusercontent.com/45220025/96666699-417c1e80-138a-11eb-95e9-a95a5b4e0711.png)

**Comment by loicroybon** [comment]
> I modify the pick here, the mobile terminal can be used normally;
> ![image](https://user-images.githubusercontent.com/45220025/96666699-417c1e80-138a-11eb-95e9-a95a5b4e0711.png)

Thanks a lot ! It was that !

**Comment by midnight-dev** [comment]
It's that pesky depth frag extension again. Even when mobile devices have the hardware available, the OpenGL ES 1.0 / 2.0 that they run doesn't have the extension enabled. It shouldn't be a problem when WebGPU is officially spec'd and supported in major browsers. For now, WebGL is the only standard, and it's showing its age.

Of the limited options, the easiest one would be to test for mobile user agents and substitute compatible code in place of the problematic stuff. For example, force the HQ splats to fallback to standard quality and parabolic shaped points to be square or circle.

Thanks for sharing your findings @Paweled
