### ISSUE TITLE
Issue with LAZ format on S3 bucket

### ISSUE THREAD

**Issue by julesmorel** [potree/potree#929]
I am converting point clouds using Potree Converter 1.7 then storing the result on an public S3 bucket.
While converting in binary, no problem occurs and the point clouds are correctly displayed.
However, if I convert with '--output-format LAZ' option, the results are correctly produced and again stored on a public S3 bucket, but once loaded in Potree (current branch develop), only few points appears. It seems like only one node of the octree is displayed. 
No error appears in the browser console. 
Any hint on how to solve this problem is welcome.

**Comment by midnight-dev** [comment]
There _shouldn't_ me a disparity between the two formats in the final graphical result, but the backend loader is different; so there's _potential_ for something to be glitched. Let's run a few tests before we crack open the loader. 

1. What happens when you convert to LAS format (not LAZ) and serve it from the S3 bucket in the same way? This would help identify if it's the compression/decompression that's affecting the loading or rendering.

2. Is there any difference when running a localhost server and serving the point clouds from there? This would point towards a CORS, security, or public permission issue.

3. If you modify the HTML/JavaScript (the stuff that initializes the point cloud) to load many more points, like 10 million instead of 1 million, does this help or hurt in any noticeable way? Please also modify minimum node size to 0; setting this value either through the GUI or from JavaScript will tell Potree to traverse and render nodes even when the bounding box of the node is so small that it takes up effectively 0px. Changes here would point to the engine following directions, believing that it's acting appropriately but still having an undesirable effect - to which the solution may be to just ask for more points. I don't know why this would be different between binary and LAZ formats, but I cannot rule it out yet. 

4. If it doesn't take a long time, can you cut out a piece inside CloudCompare and convert it to see if this problem occurs in the same way? If so, I'd like to take a look at a small sample to help get to the bottom of this issue. This wouldn't point me in an obvious direction, but it would allow me to investigate this behavior.

5. Is there any difference if you set the active attribute to something like elevation or point source ID? I'm curious of whether this could be a shader or color issue.

Tip: you can quickly get a visual idea of the number and size of geometry nodes by enabling the "Box" checkbox. It's either in the appearance or tools. If you don't change the camera location, you can compare what the initial load-in looks like by turning this on and switching between tabs with each version loaded. I believe this would point toward an actual difference in topology, point count/budget, or min node size. It could also help highlight errors in the converted files.

**Comment by julesmorel** [comment]
Thank you for the detailed explanation. Following your advises (in particular the 2), I managed to track down the bug: it is not related to potree or potreeConverter, but it's due to my way to give access to the converted files. 
I am closing the issue

**Comment by midnight-dev** [comment]
Happy to help!
