### ISSUE TITLE
Potree 1.7.x not running on iOS devices

### ISSUE THREAD

**Issue by foxxis** [potree/potree#956]
Hi all,

We have noted that Potree will not run in any major browser on iOS devices running later iOS versions (14.x)
There are at least two problems:

1. All iOS browsers derive from webkit in some manner, and Safari as standard does not run WebGL2. Enabling WebGL2 in advanced settings does enable Potree to at least load in iOS Safari.
2. OctreeLoader relies on BigInt64 which is not present in native javascript on iOS. It leads to throwing the following error:
`[Error] Unhandled Promise Rejection: TypeError: view.getBigInt64 is not a function. (In 'view.getBigInt64(i * bytesPerNode + 6, true)', 'view.getBigInt64' is undefined)
	(anonymous function) (potree.js:14383) 
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob`
Which is triggered in Ocreeloader at line 390.

Has anyone successfully managed to run Potree 1.7.x on an iOS device by mitigating the above error (with a polyfill for example)?

Thanks in advance!

**Comment by potree** [comment]
Hi, iOS/mac devices are not supported because they are usually quite a bit behind Firefox and Chrome in implementing the standard, and because I don't have these devices myself to test with.

**Comment by foxxis** [comment]
So it is not of interest for the project to attempt to support this? I assume there are other contributors or is this a solo effort?
Like it or not: iOS devices are widely used in sectors interested in point clouds and addressing compatibility would benefit adoption.

I really like the project and would like to contribute, but getting a constructive issue report closed after an hour with a "sorry, not support as I personally have no devices" feels a bit strange for an open source project.

**Comment by foxxis** [comment]
@potree ping since closed.

**Comment by potree** [comment]
> So it is not of interest for the project to attempt to support this? 

Unless someone would fund this, no. The problem is that supporting old technology severely impacts my ability to get stuff done, which is why I can't officially support ios devices. Sometimes older versions start to work.

**Comment by potree** [comment]
> feels a bit strange for an open source project.

Although Open Source, it's mostly by myself for multiple reasons. One is that verifying and maintaining third party contributions is an enormous effort that I'm rarely paid for. The other is that my main interest lies in researching and exploring rendering algorithms so I have limited time to provide support for all systems, so I'm focusing on Firefox and Chrome, which are not really available on ios.

**Comment by potree** [comment]
As for your second problem ```OctreeLoader relies on BigInt64 which is not present in native javascript on iOS. ```, you might get around this by using the old Potree format using PotreeConverter 1.7. The new one uses int64 because the hierarchy stores offsets and sizes of nodes inside octree.bin in 64 bit integers.

**Comment by midnight-dev** [comment]
> We have noted that Potree will not run in any major browser on iOS devices running later iOS versions (14.x)
> There are at least two problems:
> 
> 1. All iOS browsers derive from webkit in some manner, and Safari as standard does not run WebGL2. Enabling WebGL2 in advanced settings does enable Potree to at least load in iOS Safari.

This may be an issue with a particular WebGL extension that we've seen affect many mobile devices (Android & iOS). By the way, I wouldn't rely on Safari as a measure of compatibility. Much of the WebGL 2 spec is intentionally not implemented in Safari, and last I checked, there were no plans to work on it despite every other major browser having it... But that's another gripe for another time. 

**Try disabling Eye Dome Lighting (EDL) and use standard quality splats, not the high quality rendering mode.** Most of the example HTML files have EDL enabled by default. Although it improves the visual quality of point clouds, it requires a WebGL extension to run depth calculations for fragment shaders. Even with hardware that is absolutely capable of running these calculations, Android and Apple devices use an embedded systems version of OpenGL which doesn't have support for the frag depth extension. That could be what's going on here.

> 2. OctreeLoader relies on BigInt64 which is not present in native javascript on iOS. It leads to throwing the following error:
>        `[Error] Unhandled Promise Rejection: TypeError: view.getBigInt64 is not a function. (In 'view.getBigInt64(i * bytesPerNode + 6, true)', 'view.getBigInt64' is undefined) (anonymous function) (potree.js:14383)  asyncFunctionResume (anonymous function) promiseReactionJobWithoutPromise promiseReactionJob`
>        Which is triggered in Ocreeloader at line 390.

Unfortunately, I'm not aware of a quick workaround for this. It may be a good idea to guard against this problem by checking for BigInt64 support before requesting it from the browser. Something to tack onto the TODO list, but like Markus laid out, trying to Apple-proof the project is not exactly a priority. Personally, even if I could afford a new iPhone, I doubt that I'd ever buy one since the entire platform heavily restricts users in favor of protecting them from themselves. And because I can't install iOS or iPadOS or MacOS on any device I currently have, I can't even diagnose issues or test possible solutions.

Although not exactly a _fix_, maybe this can be side-stepped by going back to an earlier version before 1.7 was officially released. I looked through some of the commits around 1.7 beta and found that this is the latest commit where the loader doesn't reference the `getBigInt64` method: b223579e0d8cbed34d5ac58a6121d499b4bc76cf (checkout/download this version and build the JS fresh). Of course, this would mean you can't expect compatibility with point clouds converted into the new PotreeConverter 2.0 format. And some fixes/tweaks since April of last year will not be part of the engine, but the majority of the 300+ improvements since 1.6 will still be there.

> Like it or not: iOS devices are widely used in sectors interested in point clouds and addressing compatibility would benefit adoption.

This is a known bug in Humanity 1.0. The temporary solution is to slap them around with a trout until they put down the iPhone.

---

> I really like the project and would like to contribute, but getting a constructive issue report closed after an hour with a "sorry, not support as I personally have no devices" feels a bit strange for an open source project.

It's not that issues get closed if they're inconvenient. Everyone who actively watches this repository has likely seen a non-trivial amount of issues reporting that Potree doesn't work on iOS or Safari. For any project, there has to be a balance of investing time & effort versus the health & growth of the project. For this issue specifically, I think there is a significant imbalance when the problem can be ~solved~ avoided by asking "Could you try it on a laptop or PC?" Though that's a blunt way of looking at it, I'm not trying to be rude, really. Just trying to ascribe a method to the madness. So many open source projects end up being abandoned from burnout; that unyielding feeling of anxiety, apathy, and spite tends to crop up when juggling every bug report, suggestion, and feature request at the same time. Triage can help keep things manageable; part of that is inevitably gonna include closing compatibility problems which stem from Apple platforms. Likewise for reports about Potree not working in Internet Explorer (though it, too, is used in enterprise industries despite the wishes of every IT department).

Notwithstanding the above, there is still room for optimism. Many forks of Potree exist - some going in different directions. The [pnext/three-loader](https://github.com/pnext/three-loader) fork provides a Potree loader & decoder but in TypeScript and without a coupled UI. It's a bit behind any recent edition of Potree because features have to be manually ported over. It's worth checking out. Plus, we're about to see things get interesting. A new era with a new graphics specification for browsers is just around the corner. The WebGPU spec seeks to be supported by every major web browser, and it should be substantially better than WebGL. Compute shaders, high performance with modern design, and granular API abstraction for DirectX, Vulkan / OpenGL, and Metal. Although it's still cooking in the oven, WebGPU is already available in nightly builds of Firefox and Chrome. Only a matter of time until the spec is finalized & deployed by all vendors for x86 and ARM architectures. Speaking of which, with the WebGPU version of Potree already being prototyped, this will hopefully be moot issue given enough time. Until then, submitting a pull request with a clear explanation is probably the best way to address immediate concerns.

**Comment by hyemhyemu** [comment]
Here is some hints for people like me working on potree for both Android and iOS platform. I was struggling to open potree site on iPhone/iPad, the following is my recent attempt, hopefully this will work for you guys too.

Step 1. Enable WebGL2 in Settings, https://www.youtube.com/watch?v=44jaS1eloy8
Step 2. Update your iOS device to at least 15.0 ver
(I’m currently using Potree 1.8)

Good luck to you all, and also great thanks to the open source Potree!
