### ISSUE TITLE
Warning in 1.8

### ISSUE THREAD

**Issue by jtogle** [potree/potree#969]
I'm excited about implementing WebXR in release 1.8, but am having a bit of trouble. As you can see in the attached screenshot, my point cloud does render in the div just below the sad kitty, but the menu is completely bonkers. I'm getting warnings about the mime-type of the stylesheets and with invalid WebGL Framebuffer operation. My point cloud was generated by using Potree Desktop to convert from a .las, and it displays beautifully in Potree Desktop. I've checked that I didn't leave any paths broken. Can anyone advise?

![Screenshot 2021-01-31 133749](https://user-images.githubusercontent.com/18631073/106394270-b7504700-63c9-11eb-9215-18ebf52925da.jpg)
![Screenshot 2021-01-31 133725](https://user-images.githubusercontent.com/18631073/106394271-b7e8dd80-63c9-11eb-828d-377bf48c12ad.jpg)

**Comment by midnight-dev** [comment]
The menu wigging out is due to problems with CSS. As the warnings indicate, the server is sending the files in octet streams, which is usually suitable for binary downloads or media streaming. Double check that there isn't a weird `.htaccess` rule (if Apache) that serves those text files as binary downloads. If you uploaded the files via FTP, check that the CSS files were uploaded as ASCII rather than binary - it's usually an automatic mode that determines this, but it can always be manually overridden. I haven't had a server force a MIME type just based on how they were uploaded, but it's worth a look. If you pre-compressed the files, they could also be interpreted as downloads instead of stylesheets. 

As for the WebGL issues, I can't speak on the stability of this version. Since 1.7, it looks like the author made a lot of commits relating to rendering. It could be a problem with the WebXR implementation, the software/hardware used, or the latest ThreeJS r124. Can you reproduce the warnings with a different browser or headset?

**Comment by jtogle** [comment]
My sys admins have my file access such that I use Webdrive to access this server. I'll check the settings there as what you are saying makes a lot of sense. It is definitely CSS sadness, and if the files are getting converted to binary during the transfer that would do it. Thanks, I'll see if I can address that possibility!

**Comment by jtogle** [comment]
Well, I see nothing in Webdrive to indicate that it is intentionally borking ASCII files, and the stylesheets on the server seem to be ASCII, so I'm stumped on that one. It is definitely a problem with styles though.

**Comment by midnight-dev** [comment]
That's a bummer, but there are a couple of reasonable workarounds. The CSS shouldn't have changed much since last release (if at all), so you could link to a previous deployment's CSS instead. Alternatively, copy the contents of each file to a `<style>` block inside the HTML file. It's not an actual solution, but it should treat the symptom & let you use the menu for now. If you don't have much direct access to the server, ask a sysadmin if they can figure out why the server is sending out CSS files as downloads. There may be an ancient, well-forgotten configuration that is causing the MIME mix up.

**Comment by jtogle** [comment]
Good point. I never implement 1.7 but have quite a few clouds shared via 1.6. I'll try pointing to those files and see what I get. I'll keep this issue open until it is resolved in case my problem isn't entirely self-inflicted or could serve as a non-example for others.

**Comment by jtogle** [comment]
OK, this is resolved. It was indeed that the file mime types were getting messed up during file transfer. Everything is sorted now. Thanks! Here's the pointcloud I was trying to display: https://viz.lib.vt.edu/1_8/vauquois/wolf.html
